export class Language {

    static defaultlang = {
        eng: {
            setyuyan: "Language settings",
            huanyin: "Welcome to intelligent film cutting machine",
            qssjh: "Please enter your mobile number",
            qd: "Determine",
            qsxm: "Please enter your name",
            qsrzhmm: "Please enter your account password",
            zuihousj: "Last device update time",
            moren: "default",
            qcz: "To recharge",
            cishu: "second",
            xiugai: "modify",
            csbzqcz: "Insufficient cutting times, please purchase as soon as possible",
            fsklwj: "Send burn file",
            sxz: "Refresh",
            sxzt: "Refresh Status",
            user: "Use",
            gybj: "About this machine",
            wxts: "Warm tip: to protect your rights and interests, please improve your personal data. If you forget your password, you can retrieve it by verifying your personal data!",
            qsdz: "Please enter your address",
            qsyx: "Please enter your email",
            qshm: "Please enter your mobile number",
            dz: "address",
            yx: "mailbox",
            phone: "Telephone",
            name: "Full name",
            wsgrzl: "Improve personal data",
            tj: "Statistics",
            cp: "product",
            szcsyzmm: "Setting parameters requires entering a password to verify your permissions",
            tcdl: "Logout",
            tsms: "Enter debugging mode",
            sbpz: "Equipment configuration",
            grzl: "personal data",
            sycs: "Remaining cutting times",
            wode: "My",
            sp: "commodity",
            jsgy: "Nearly 3 months",
            jygy: "Nearly 1 months",
            jqt: "Nearly 7 days",
            xl: "Sales volume",
            rq: "date",
            spxl: "Commodity sales volume",
            mrxl: "Daily sales volume",
            fenlei: "classification",
            sksb: "Try to carve failed, please check whether the machine is connected to the network normally",
            zlxd: "Try to carve the following instructions",
            cyxh: "Common models",
            remenxh: "Popular models",
            nownobang: "There is currently no binding device",
            lx: "Off-line",
            zaixian: "On-line",
            yilianjie: "Connected device",
            sousuozhong: "Device searching",
            czok: "Reset success",
            querencz: "Are you sure to reset? Configuration information for your machine will be lost",
            geshihua: "Restore factory settings",
            xianweikaiguan: "Limit switch",
            sbbuzaixian: "Device not online",
            weibangshebei: "Unbound device",
            setfukuan: "Width of cloth",
            setsudu: "speed",
            setcanshu: "Parameter setting",
            shuzhi: "Value:",
            daoyaname5: "Name of knife press 5:",
            daoyaname4: "Name of knife press 4:",
            daoyaname3: "Name of knife press 3:",
            daoyaname2: "Name of knife press 2:",
            daoyaname1: "Name of knife pressure I:",
            setdaoya: "Knife pressure setting",
            yzhou: "Y axis",
            xzhou: "X axis",
            shebeilixian: "Device is offline",
            nobang: "Unbound device",
            setchilunbi: "Gear ratio setting",
            jieguo: "search result",
            quxiao: "cancel",
            shuhao: "Please enter brand / model keywords",
            chongqianno: "Recharge failed!",
            chongqianok: "Recharge succeeded!",
            nowchong: "Immediate payment",
            qianxieyi: "Recharge agreement",
            tongyi: "By clicking pay now, you agree",
            qian3: "3. After recharging, no refund without reason is supported.",
            qian2: "2. The number of times cannot be exchanged for cash, withdrawn or transferred to others.",
            qian1: "1. The purchase times can be used for film cutting.",
            tishi: "Reminder",
            xuanqian: "Please select the recharge amount",
            tijiaook: "Submit successfully",
            queren: "Confirm submission",
            huifu: "Reply:",
            lishifankui: "Historical feedback",
            tianyijian: "Please fill in your comments and suggestions here",
            tijiao: "Submission",
            fankui: "Feedback",
            chongqian: "Recharge",
            qiemojilu: "Cutting film recording",
            chongzhijilu: "Recharge record",
            shengcishu: "Residual times",
            mimacuo: "Username or password incorrect",
            denglu: "Sign in",
            shumima: "Please input a password",
            shuzhanghu: "Please enter account",
            wangjimima: "Forget password",
            password: "Password",
            zhanghu: "account",
            qingdenglu: "Please login",
            nolianjie: "Unconnected",
            shuruidshebei: "Please enter the device name / ID to find the devic",
            wodezhanghu: "My account",
            xuanzejiqi: "Select the current online machine",
            moshi2: "Mode 2",
            moshi1: "Mode 1",
            moshi0: "Mode 0",
            zhongzhi: "Reset",
            kelu: "Burn",
            shike: "Trial carving",
            gengxintime: "Last updated:",
            fukuan: "Width of cloth",
            xianwei: "Limit",
            chulunbi: "Gear ratio",
            daoya: "Knife pressure",
            daosu: "Cutter speed",
            shebeixinxi: "Device information",
            shuaxinshuju: "Refresh machine data",
            shebeihao: "Device number",
            zhinengqiemo: "Intelligent membrane cutting",
            noshebei: "No available devices found",
            setdaosucuo: "Error setting tool speed:",
            setdaoyacuo: "Error setting tool pressure:",
            keluchucuo: "Burn error",
            cutting: "Cutting film",
            querenqiege: "Confirm cutting",
            settishi: "Please set the tool pressure or speed first",
            tianjiaok: "Add success",
            setdaosu: "Setting knife speed",
            jianchakelu: "Check the recording status of the device",
            jianchazaixian: "Check the online status of the equipment",
            close: "Close",
            chulizhong: "Cutting data processing",
            lijiqiemo: "Immediate membrane cutting",
            lixian: "Equipment offline",
            weibangdin: "Unbound",
            back: "Return",
            shuoming: "Film cutting instructions",
            sudu: "Speed:",
            tianjiachangyon: "Add as common",
            canshu: "Cutting parameters",
            xiangqing: "Details of film cutting",
            ip2: "Equipment IP:",
            xuliehao2: "Equipment serial number:",
            shiyonzhong: "in use",
            zhaobudao: "Device information not found",
            zhengzaisousuo: "Searching now",
            tianjiashebei: "Add device",
            shebei: "Device list",
            setok: "Set up successfully",
            startset: "Set up",
            jiance: "Detect unconnected AP mode",
            changshi: "Try to connect",
            ok: "complete",
            tspassword: "Please enter WiFi password",
            tishiwifiname: "Please enter WiFi name",
            next: "Next step",
            wifipassword: "Wifi password",
            wifiname: "WiFi name",
            quebao: "Make sure you''re connected to the device hotspot",
            peizhiwifi: "Configure WiFi",
            peizhifangshi: "Select configuration mode",
            sousuo: "Search device",
            peiwang: "Distribution network for equipment",
            xinhao: "Model",
            pinpai: "brand",
            xieyi: "Protocol specification",
            shiyoncishu: "Number of knife head use",
            dianyuan: "Power Supply",
            ip: "IP address",
            xuliehao: "Equipment serial number",
            banbenhao: "Version number",
            qiemoji: "Intelligent film cutting machine",
            sz: "Set up",
            lang: "language",
            home:'Home',
            sbpw:'Equipment distribution network',
            wdsb:'My equipment',
            qrsc:'Are you sure to delete?',
            sc:'Delete',
            bc:'Preservation',
            wzdsb:'Device not found',
            ytjsb:'The device has been added',
            ycz:'Added to common, do not add again',
            sccg:'Delete successful'
        },
        chn: {
            setyuyan: "语言设置",
            huanyin: "欢迎使用智能切膜机",
            qssjh: "请输入您的手机号码",
            qd: "确定",
            qsxm: "请输入您的姓名",
            qsrzhmm: "请输入您的账户密码",
            zuihousj: "设备最后更新时间",
            moren: "默认",
            qcz: "去充值",
            cishu: "次",
            xiugai: "修改",
            csbzqcz: "切割次数不足,请尽快购买次数",
            fsklwj: "发送刻录文件",
            sxz: "刷新中",
            sxzt: "刷新状态",
            user: "使用",
            gybj: "关于本机",
            wxts: "温馨提示：为保障您的权益，请完善个人资料，忘记密码时可通过验证个人资料，找回密码！",
            qsdz: "请输入您的地址",
            qsyx: "请输入您的邮箱",
            qshm: "请输入您的手机号码",
            dz: "地址",
            yx: "邮箱",
            phone: "电话",
            name: "姓名",
            wsgrzl: "完善个人资料",
            tj: "统计",
            cp: "产品",
            szcsyzmm: "设置参数需要输入密码验证您的权限",
            tcdl: "退出登录",
            tsms: "进入调试模式",
            sbpz: "设备配置",
            grzl: "个人资料",
            sycs: "剩余切割次数",
            wode: "我的",
            sp: "商品",
            jsgy: "近3个月",
            jygy: "近1个月",
            jqt: "近7天",
            xl: "销量",
            rq: "日期",
            spxl: "商品销量",
            mrxl: "每日销量",
            fenlei: "分类",
            sksb: "试刻失败，请查看机器是否正常联网",
            zlxd: "试刻指令以下达",
            cyxh: "常用型号",
            remenxh: "热门型号",
            nownobang: "当前无绑定设备",
            lx: "离线",
            zaixian: "在线",
            yilianjie: "已连接设备",
            sousuozhong: "设备搜索中",
            czok: "重置成功",
            querencz: "确定重置？您的机器的配置信息将丢失",
            geshihua: "恢复出厂设置",
            xianweikaiguan: "限位开关",
            sbbuzaixian: "设备不在线",
            weibangshebei: "未绑定设备",
            setfukuan: "幅宽",
            setsudu: "速度",
            setcanshu: "参数设置",
            shuzhi: "数值：",
            daoyaname5: "刀压五名称：",
            daoyaname4: "刀压四名称：",
            daoyaname3: "刀压三名称：",
            daoyaname2: "刀压二名称：",
            daoyaname1: "刀压一名称：",
            setdaoya: "刀压设置",
            yzhou: "Y轴",
            xzhou: "X轴",
            shebeilixian: "设备已离线",
            nobang: "无绑定设备",
            setchilunbi: "齿轮比设置",
            jieguo: "搜索结果",
            quxiao: "取消",
            shuhao: "请输入品牌/型号关键词",
            chongqianno: "充值失败!",
            chongqianok: "充值成功!",
            nowchong: "立即支付",
            qianxieyi: "《充值协议》",
            tongyi: "点击立即支付，即表示您已经同意",
            qian3: "3.充值后，不支持无理由退款。",
            qian2: "2.次数不可兑换现金、提现或转赠他人。",
            qian1: "1.购买次数可用于切膜时使用。",
            tishi: "温馨提示",
            xuanqian: "请选择充值金额",
            tijiaook: "提交成功",
            queren: "确认提交",
            huifu: "回复：",
            lishifankui: "历史反馈",
            tianyijian: "请在此填写您的意见和建议…",
            tijiao: "提交",
            fankui: "意见反馈",
            chongqian: "充值",
            qiemojilu: "切膜记录",
            chongzhijilu: "充值记录",
            shengcishu: "剩余次数",
            mimacuo: "用户名或密码不正确",
            denglu: "登录",
            shumima: "请输入密码",
            shuzhanghu: "请输入账户",
            wangjimima: "忘记密码",
            password: "密码",
            zhanghu: "账户",
            qingdenglu: "请登录",
            nolianjie: "未连接",
            shuruidshebei: "请输入设备名称/ID查找设备",
            wodezhanghu: "我的账户",
            xuanzejiqi: "选择当前在线机器",
            moshi2: "模式2",
            moshi1: "模式1",
            moshi0: "模式0",
            zhongzhi: "重置",
            kelu: "刻录",
            shike: "试刻",
            gengxintime: "最后更新时间：",
            fukuan: "幅宽",
            xianwei: "限位",
            chulunbi: "齿轮比",
            daoya: "刀压",
            daosu: "刀速",
            shebeixinxi: "设备信息",
            shuaxinshuju: "刷新机器数据",
            shebeihao: "设备号",
            zhinengqiemo: "智能切膜",
            noshebei: "找不到可用设备",
            setdaosucuo: "设置刀速出错：",
            setdaoyacuo: "设置刀压出错：",
            keluchucuo: "刻录出错",
            cutting: "正在切膜",
            querenqiege: "确认切割",
            settishi: "请先设置刀压或者速度",
            tianjiaok: "添加成功",
            setdaosu: "设置刀速",
            jianchakelu: "检查设备刻录状态",
            jianchazaixian: "检查设备在线状态",
            close: "关闭",
            chulizhong: "切割数据处理中",
            lijiqiemo: "立即切膜",
            lixian: "设备离线",
            weibangdin: "未绑定",
            back: "返回",
            shuoming: "切膜说明",
            sudu: "速度：",
            tianjiachangyon: "添加为常用",
            canshu: "切膜参数",
            xiangqing: "切膜详情",
            ip2: "设备ip：",
            xuliehao2: "设备序列号：",
            shiyonzhong: "使用中",
            zhaobudao: "找不到设备信息",
            zhengzaisousuo: "正在搜索",
            tianjiashebei: "添加设备",
            shebei: "设备列表",
            setok: "设置成功",
            startset: "开始设置",
            jiance: "检测未连接AP模式",
            changshi: "尝试连接",
            ok: "完成",
            tspassword: "请输入WiFi密码",
            tishiwifiname: "请输入wifi名称",
            next: "下一步",
            wifipassword: "WiFi密码",
            wifiname: "WiFi名称",
            quebao: "确保你已经连上设备热点",
            peizhiwifi: "配置wifi",
            peizhifangshi: "选择配置方式",
            sousuo: "搜索设备",
            peiwang: "为设备进行配网",
            xinhao: "型号",
            pinpai: "品牌",
            xieyi: "协议说明",
            shiyoncishu: "刀头使用次数",
            dianyuan: "电源",
            ip: "IP地址",
            xuliehao: "设备序列号",
            banbenhao: "版本号",
            qiemoji: "智能切膜机",
            sz: "设置",
            lang: "语言",
            home:'首页',
            sbpw:'设备配网',
            wdsb:'我的设备',
            qrsc:'确认删除吗？',
            sc:'删除',
            bc:'保存',
            wzdsb:'未找到设备',
            ytjsb:'已添加该设备',
            ycz:'已添加至常用，请勿重复添加',
            sccg:'删除成功'
        },
        esp: {
            setyuyan: "Configuración del idioma",
            huanyin: "Los cortadores de membranas inteligentes son bienvenidos",
            qssjh: "Por favor, introduzca su número de teléfono celular",
            qd: "determinar",
            qsxm: "Por favor, introduzca su nombre",
            qsrzhmm: "Por favor introduzca la contraseña de su cuenta",
            zuihousj: "Hora de la última actualización del dispositivo",
            moren: "Por omisión",
            qcz: "desrecarga",
            cishu: "veces",
            xiugai: "La modificación",
            csbzqcz: "El número de cortes es insuficiente, por favor compre el número tan pronto como sea posible",
            fsklwj: "Envía archivos de grabación",
            sxz: "En proceso de actualización",
            sxzt: "Estado de actualización",
            user: "El uso de",
            gybj: "Acerca de la máquina",
            wxts: "Consejos: para proteger sus derechos, por favor, perfeccione sus datos personales.",
            qsdz: "Por favor, introduzca su dirección",
            qsyx: "Por favor, introduzca su correo electrónico",
            qshm: "Por favor ingrese su número de teléfono",
            dz: "dirección",
            yx: "dirección",
            phone: "Tel.",
            name: "Los nombres",
            wsgrzl: "Mejora de los datos personales",
            tj: "estadísticas",
            cp: "productos",
            szcsyzmm: "La configuración de los parámetros requiere la entrada de una contraseña para verificar sus permisos",
            tcdl: "Salida del inicio de sesión",
            tsms: "Entrar en el modo de depuración",
            sbpz: "Configuración del equipo",
            grzl: "Datos personales",
            sycs: "Número de cortes restantes",
            wode: "mi",
            sp: "Los productos",
            jsgy: "Casi 3 meses",
            jygy: "Casi UN mes",
            jqt: "Casi 7 días",
            xl: "Las ventas",
            rq: "fecha",
            spxl: "Volumen de ventas de mercancías",
            mrxl: "Volumen diario de ventas",
            fenlei: "clasificación",
            sksb: "El ensayo ha fallado, por favor verifique si la máquina está conectada correctamente",
            zlxd: "Intenta grabar las instrucciones siguientes hasta",
            cyxh: "Modelos comunes",
            remenxh: "Modelos populares",
            nownobang: "Dispositivo actualmente no vinculado",
            lx: "desconectado",
            zaixian: "En línea",
            yilianjie: "Dispositivos conectados",
            sousuozhong: "Búsqueda de dispositivos",
            czok: "Restablecimiento exitoso",
            querencz: "¿UN reinicio definitivo? La información de configuración de su máquina se perderá",
            geshihua: "Restablecimiento de la configuración de fábrica",
            xianweikaiguan: "Interruptor de límite",
            sbbuzaixian: "El dispositivo no está en línea",
            weibangshebei: "Dispositivos no vinculados",
            setfukuan: "FuKuan",
            setsudu: "velocidad",
            setcanshu: "Ajuste de parámetros",
            shuzhi: "Valores numéricos:",
            daoyaname5: "Cuchillo clavado cinco nombres:",
            daoyaname4: "Cuchillo presión cuatro nombres:",
            daoyaname3: "Cuchillo presión tres nombres:",
            daoyaname2: "Cuchillo presión dos nombres:",
            daoyaname1: "Cuchillo para presionar UN nombre:",
            setdaoya: "Ajuste de la presión del cuchillo",
            yzhou: "Eje Y.",
            xzhou: "Los ejes X",
            shebeilixian: "El equipo está fuera de línea",
            nobang: "Dispositivos no vinculados",
            setchilunbi: "Relación de marcha",
            jieguo: "Resultados de la búsqueda",
            quxiao: "cancelación",
            shuhao: "Por favor, introduzca la palabra clave marca/modelo",
            chongqianno: "¡La recarga ha fallado!",
            chongqianok: "¡Recarga exitosa!",
            nowchong: "Pago inmediato",
            qianxieyi: "«Acuerdo de recarga»",
            tongyi: "Al hacer clic en pagar ahora, usted está de acuerdo",
            qian3: "3. después de recargar el valor, no se admitirá ningún reembolso sin justificación.",
            qian2: "2. la frecuencia no es convertible en efectivo, retiros o transferencias a otras personas.",
            qian1: "1. el número de compras se puede utilizar para cortar la membrana.",
            tishi: "Consejos cálidos",
            xuanqian: "Por favor seleccione en cantidad",
            tijiaook: "Presentación exitosa",
            queren: "Confirmación de la presentación",
            huifu: "Respuesta:",
            lishifankui: "Retroalimentación histórica",
            tianyijian: "Por favor rellene este las observaciones y sugerencias.",
            tijiao: "presentación",
            fankui: "comentarios",
            chongqian: "en",
            qiemojilu: "Registro del corte de la membrana",
            chongzhijilu: "Registro de recarga",
            shengcishu: "Número restante",
            mimacuo: "El nombre de usuario o la contraseña no son correctos",
            denglu: "inicio",
            shumima: "Por favor, introduzca su contraseña",
            shuzhanghu: "Por favor ingrese su cuenta",
            wangjimima: "Olvidó su contraseña",
            password: "La contraseña",
            zhanghu: "Las cuentas",
            qingdenglu: "Por favor, inicie sesión",
            nolianjie: "Sin conexión",
            shuruidshebei: "Por favor, introduzca el nombre /ID del dispositivo para encontrar el dispositivo",
            wodezhanghu: "Mi cuenta",
            xuanzejiqi: "Seleccione la máquina en línea actual",
            moshi2: "Modo 2",
            moshi1: "Modo 1",
            moshi0: "Modo 0",
            zhongzhi: "restaurar",
            kelu: "graba",
            shike: "Intenta grabar",
            gengxintime: "Última actualización:",
            fukuan: "FuKuan",
            xianwei: "XianWei",
            chulunbi: "Relación de marcha",
            daoya: "Cuchillo clavado",
            daosu: "Cuchillo de",
            shebeixinxi: "Información sobre el dispositivo",
            shuaxinshuju: "Actualizar la máquina de datos",
            shebeihao: "Número de dispositivo",
            zhinengqiemo: "Membrana de corte inteligente",
            noshebei: "No se pudo encontrar equipo disponible",
            setdaosucuo: "Cuchillo de errores:",
            setdaoyacuo: "Error en la configuración de la presión del cuchillo:",
            keluchucuo: "Grabar UN error",
            cutting: "Cortar la membrana",
            querenqiege: "Confirmación del corte",
            settishi: "Por favor antes de cuchillo clavado o velocidad",
            tianjiaok: "Añadir éxito",
            setdaosu: "Ajuste de la velocidad de la cuchilla",
            jianchakelu: "Compruebe el estado de grabación del dispositivo",
            jianchazaixian: "Compruebe el estado de los dispositivos en línea",
            close: "cierre",
            chulizhong: "Cortar en el procesamiento de datos",
            lijiqiemo: "Corte inmediato de la membrana",
            lixian: "Equipo fuera de línea",
            weibangdin: "Sin atar",
            back: "regreso",
            shuoming: "La nota de membrana",
            sudu: "Velocidad:",
            tianjiachangyon: "Añadir habitual",
            canshu: "El parámetro de membrana",
            xiangqing: "Detalles de la membrana",
            ip2: "Ip del dispositivo:",
            xuliehao2: "Número de serie del dispositivo:",
            shiyonzhong: "Se utiliza",
            zhaobudao: "Se puede encontrar información del dispositivo",
            zhengzaisousuo: "Búsqueda en curso",
            tianjiashebei: "Añadir UN dispositivo",
            shebei: "Lista de equipo",
            setok: "Puesta en marcha con éxito",
            startset: "Comenzar la configuración",
            jiance: "Detección del modo AP no conectado",
            changshi: "Intentos de conexión",
            ok: "completar",
            tspassword: "Por favor ingrese WiFi contraseña",
            tishiwifiname: "Por favor ingrese el nombre del wifi",
            next: "El siguiente paso",
            wifipassword: "WiFi contraseña",
            wifiname: "Nombre WiFi",
            quebao: "Asegúrese de que ya ni el equipo de",
            peizhiwifi: "Configuración wifi",
            peizhifangshi: "Seleccione la configuración de forma",
            sousuo: "El equipo de búsqueda",
            peiwang: "Aparatos para merecer la red",
            xinhao: "El modelo",
            pinpai: "La marca",
            xieyi: "Acuerdo sobre",
            shiyoncishu: "DaoTou usando el número",
            dianyuan: "alimentación",
            ip: "La dirección IP",
            xuliehao: "Equipamiento de serie",
            banbenhao: "La versión",
            qiemoji: "La máquina de membrana inteligente",
            sz: "La configuración",
            lang: "El lenguaje", 
            home:'Home',
            sbpw:'Red de distribución',
            wdsb:'Mi equipo.',
            qrsc:'Confirma la supresión?',
            sc:'Eliminar',
            bc:'Guardar',
            wzdsb:'Dispositivo no encontrado',
            ytjsb:'Añadir el dispositivo',
            ycz:'Por favor, no lo repita.',
            sccg:'Borrar éxito'
        },
        por: {
            setyuyan: "Definição da língua",
            huanyin: "Os cortadores de membrana inteligentes são bem-vindos",
            qssjh: "Por favor, digite o seu número de telefone celular",
            qd: "A certeza",
            qsxm: "Por favor, insira seu nome",
            qsrzhmm: "Por favor, insira a senha da sua conta",
            zuihousj: "Hora da última atualização do dispositivo",
            moren: "Por omissão",
            qcz: "desrecarga",
            cishu: "vez",
            xiugai: "alterações",
            csbzqcz: "Corte insuficiente, por favor, compre o número de vezes o mais rápido possível",
            fsklwj: "Envia o ficheiro gravado",
            sxz: "A actualizar.",
            sxzt: "Estado de actualização",
            user: "utilização",
            gybj: "Sobre a máquina",
            wxts: "Dica: para proteger os seus direitos e interesses, por favor, aperfeiçoar os seus dados pessoais. se esquecer a sua senha, pode verificar os seus dados pessoais e recuperar a sua senha!",
            qsdz: "Por favor, insira o seu endereço",
            qsyx: "Por favor, insira a sua caixa de correio",
            qshm: "Por favor, digite o seu número de telefone celular",
            dz: "endereço",
            yx: "Caixa de correio",
            phone: "O telefone",
            name: "O nome",
            wsgrzl: "Melhorar os dados pessoais",
            tj: "estatística",
            cp: "produtos",
            szcsyzmm: "Para definir os parâmetros, é necessário introduzir uma senha para verificar a sua permissão",
            tcdl: "Saída do login",
            tsms: "Entrar em modo de depuração.",
            sbpz: "Configuração do equipamento",
            grzl: "Dados pessoais",
            sycs: "Número de cortes restantes",
            wode: "O meu",
            sp: "produtos",
            jsgy: "Quase 3 meses",
            jygy: "Quase um mês",
            jqt: "Nos últimos 7 dias",
            xl: "De vendas",
            rq: "data",
            spxl: "Volume de vendas de mercadorias",
            mrxl: "Volume diário de vendas",
            fenlei: "classificação",
            sksb: "A tentativa falhou, por favor verifique se a máquina está conectada à rede",
            zlxd: "As instruções estão abaixo",
            cyxh: "Modelos comuns",
            remenxh: "Modelos quentes",
            nownobang: "Dispositivo actualmente não ligado",
            lx: "desligado",
            zaixian: "online",
            yilianjie: "Equipamento ligado",
            sousuozhong: "Equipamento em busca.",
            czok: "Reinicialização bem sucedida.",
            querencz: "Reiniciar? As informações de configuração da sua máquina serão perdidas",
            geshihua: "Restabelecimento da configuração de saída da fábrica",
            xianweikaiguan: "Interruptor de limitação de velocidade",
            sbbuzaixian: "O dispositivo não está em linha",
            weibangshebei: "Dispositivos não ligados",
            setfukuan: "largura",
            setsudu: "velocidade",
            setcanshu: "Definição dos parâmetros",
            shuzhi: "Valores numéricos:",
            daoyaname5: "Pressão de faca cinco nomes:",
            daoyaname4: "Pressão de faca quatro nomes:",
            daoyaname3: "Pressão de faca três nomes:",
            daoyaname2: "Pressão de faca ii nome:",
            daoyaname1: "Pressão de faca 1 nome:",
            setdaoya: "Regulação da pressão da faca",
            yzhou: "Eixo Y",
            xzhou: "Eixo X",
            shebeilixian: "O equipamento está offline",
            nobang: "Dispositivos não ligados",
            setchilunbi: "Regulação da relação de velocidades",
            jieguo: "Resultados da pesquisa",
            quxiao: "cancelar",
            shuhao: "Por favor, digite as palavras-chave da marca/modelo",
            chongqianno: "Recarga falhada!",
            chongqianok: "Recarga bem sucedida!",
            nowchong: "Pagamento imediato",
            qianxieyi: "«Acordo de recarga»",
            tongyi: "Clique no pagamento imediato, ou seja, significa que você aceitou",
            qian3: "3. após o recarregamento, o reembolso sem motivo não é suportado.",
            qian2: "Número 2, não desconte, retirada ou exemplos de outros.",
            qian1: "1. o número de compras pode ser usado durante o corte de membrana.",
            tishi: "Dica gentil",
            xuanqian: "Por favor, escolha do montante adicional",
            tijiaook: "Submissão aceite",
            queren: "Confirmação da apresentação",
            huifu: "Resposta:",
            lishifankui: "Feedback histórico",
            tianyijian: "Por favor, preencha aqui seus comentários e sugestões …",
            tijiao: "apresentação",
            fankui: "Comentários e feedback",
            chongqian: "Para recarregar",
            qiemojilu: "Registo do corte da membrana",
            chongzhijilu: "Registo da recarga",
            shengcishu: "Número restante",
            mimacuo: "O nome de usuário ou senha não está correto",
            denglu: "autenticação",
            shumima: "Por favor, digite a senha.",
            shuzhanghu: "Por favor, digite a conta.",
            wangjimima: "Esquece o código.",
            password: "senha",
            zhanghu: "conta",
            qingdenglu: "Por favor, entre.",
            nolianjie: "Não ligado",
            shuruidshebei: "Por favor, digite o nome do dispositivo/ID encontrar equipamentos",
            wodezhanghu: "A minha conta.",
            xuanzejiqi: "Selecione a máquina on-line atual",
            moshi2: "O modelo 2",
            moshi1: "Modo 1",
            moshi0: "Modo 0",
            zhongzhi: "substituição",
            kelu: "Gravá-las",
            shike: "Tentou esculpir",
            gengxintime: "Última atualização:",
            fukuan: "largura",
            xianwei: "limite",
            chulunbi: "Relação de transmissão",
            daoya: "Faca de pressão",
            daosu: "Faca velocidade",
            shebeixinxi: "Informações sobre o equipamento",
            shuaxinshuju: "Refresque os dados da máquina",
            shebeihao: "Número do dispositivo",
            zhinengqiemo: "Membrana de corte inteligente",
            noshebei: "O equipamento disponível não pôde ser encontrado",
            setdaosucuo: "Erro de configuração velocidade faca:",
            setdaoyacuo: "Erro de configuração faca pressão:",
            keluchucuo: "Tal erro",
            cutting: "A cortar a membrana.",
            querenqiege: "Confirmar a cortar",
            settishi: "Por favor, primeiro conjunto faca ou velocidade",
            tianjiaok: "Adicionar sucesso",
            setdaosu: "Velocidade da faca.",
            jianchakelu: "Equipamento de inspecção, tal estado",
            jianchazaixian: "Verificar equipamento online",
            close: "encerramento",
            chulizhong: "Processamento de dados de corte",
            lijiqiemo: "Cortar a membrana imediatamente",
            lixian: "Equipamento off-line",
            weibangdin: "Não ligado",
            back: "regresso",
            shuoming: "Instruções para o corte de membranas",
            sudu: "Velocidade:",
            tianjiachangyon: "Adicionar para uso comum",
            canshu: "Cortar a membrana parâmetros",
            xiangqing: "Cortar a membrana pormenores",
            ip2: "Equipamento de pi:",
            xuliehao2: "Equipamento de série:",
            shiyonzhong: "Em uso",
            zhaobudao: "Não consigo encontrar dispositivos de informação",
            zhengzaisousuo: "A busca",
            tianjiashebei: "equipamento",
            shebei: "Lista de dispositivos",
            setok: "Configuração sucesso",
            startset: "A configuração",
            jiance: "Detectam padrões unchained AP",
            changshi: "A tentar ligação",
            ok: "terminar",
            tspassword: "Por favor, indique a senha wi-fi",
            tishiwifiname: "Por favor, insira o nome do wifi",
            next: "O próximo passo",
            wifipassword: "Senha wi-fi",
            wifiname: "Nome do WiFi",
            quebao: "Certifique-se de que você já ligados dispositivos mais significativos",
            peizhiwifi: "Configuração do wi-fi",
            peizhifangshi: "Escolha configuração",
            sousuo: "O equipamento de busca",
            peiwang: "Para dispositivos de rede de distribuição",
            xinhao: "modelo",
            pinpai: "A marca",
            xieyi: "O acordo significa que",
            shiyoncishu: "Segmento de uso",
            dianyuan: "A energia.",
            ip: "Endereço IP",
            xuliehao: "Equipamento de série",
            banbenhao: "Número de versão",
            qiemoji: "Máquinas de cortar a membrana inteligentes",
            sz: "As configurações",
            lang: "línguas",
            home:'Página inicia',
            sbpw:'Rede de distribuição de equipamentos',
            wdsb:'Meu equipamento.',
            qrsc:'Tem certeza de apagar?',
            sc:'Deletar',
            bc:'Conservação',
            wzdsb:'Dispositivo não Encontrado',
            ytjsb:'O dispositivo FOI Adicionado',
            ycz:'Adicionado Ao comum, não adicione novamente',
            sccg:'Apagar SUCESSO'
        },
        deu: {
            setyuyan: "Sprache die",
            huanyin: "Willkommen an bord der smartphone-maschine",
            qssjh: "Bitte geben sie ihre handynummer ein",
            qd: "sicher",
            qsxm: "Bitte geben sie ihren namen ein",
            qsrzhmm: "Bitte geben sie ihr zugangspasswort ein",
            zuihousj: "Der letzte stand der aktualisierung",
            moren: "standard",
            qcz: ". Akku immer schön aufladen",
            cishu: "mal",
            xiugai: "ändern",
            csbzqcz: "Unzureichende ponpong, bitte zahlen sie so viel wie möglich ein",
            fsklwj: "Verschicken Von brenndateien",
            sxz: "Die in",
            sxzt: "Die.",
            user: "mit",
            gybj: "Über dinger",
            wxts: "Nur ein tipp: um ihre rechte zu schützen, müssen sie ihre daten verbessern, damit sie dieses passwort erhalten können, indem sie es erneut überprüfen und zurückbringen.",
            qsdz: "Bitte geben sie ihre adresse ein",
            qsyx: "Bitte geben sie ihre e-mail ein",
            qshm: "Bitte geben sie ihre handynummer ein",
            dz: "adresse",
            yx: "briefkasten",
            phone: ".",
            name: "namen",
            wsgrzl: "Die daten verbessern.",
            tj: "statistischen",
            cp: "produkte",
            szcsyzmm: "Der klick auf sofortige bezahlung ist, wenn sie schon zugestimmt haben",
            tcdl: "3. Nach dem ladevorgang wird keine rückmeldung gutgeschrieben.",
            tsms: "2. Es ist nicht bar -, einzahlbar Oder ersetzbar.",
            sbpz: "1. Die menge der einkäufe kann beim entnehmen der membran verwendet werden.",
            grzl: ". Tipp",
            sycs: "Bitte wählen sie den ladebetrag",
            wode: "Vorzulegen erfolg",
            sp: "Bestätigt vorzulegen",
            jsgy: "antwort",
            jygy: "Geschichte feedback",
            jqt: "Bitte geben sie ihre meinung und vorschläge dazu ein",
            xl: "vorzulegen",
            rq: "feedbackschleife",
            spxl: "Akku immer schön aufladen",
            mrxl: "Schneiden und.",
            fenlei: "Akku immer schön aufladen.",
            sksb: "Noch oft",
            zlxd: "Der benutzername Oder passwort ist falsch",
            cyxh: "es",
            remenxh: "Code eingeben.",
            nownobang: "Bitte geben sie ein konto ein.",
            lx: "Das passwort vergessen",
            zaixian: ".",
            yilianjie: "auf",
            sousuozhong: "zu",
            czok: "Nicht verbunden",
            querencz: "Bitte geben sie den namen des laufwerks/eine ID des suchgeräts ein",
            geshihua: "Von meiner",
            xianweikaiguan: "Wählen sie die aktuelle online-maschine aus",
            sbbuzaixian: "Modell 2",
            weibangshebei: "Modell 1",
            setfukuan: "Modell null",
            setsudu: "setzt",
            setcanshu: "auf",
            shuzhi: "Versucht.",
            daoyaname5: "Letzer aufruf:",
            daoyaname4: "幅宽",
            daoyaname3: "限位",
            daoyaname2: "Getriebe als",
            daoyaname1: ". Auf",
            setdaoya: "..",
            yzhou: "Ausrüstung informationen",
            xzhou: "Aktualisieren der maschine die daten",
            shebeilixian: "Ausrüstung.",
            nobang: "Intelligenz schneiden und",
            setchilunbi: "Maschinen nicht auffindbar",
            jieguo: "Fehler der messer.",
            quxiao: "Fehler beim klappen des messer:",
            shuhao: "Auf.",
            chongqianno: "Auf schneiden und",
            chongqianok: "Bestätigt verstümmelung",
            nowchong: "Bitte legen sie zuerst den messdruck Oder die seitengeschwindigkeit fest",
            qianxieyi: "Hinzufügen erfolg",
            tongyi: "Die. Auf",
            qian3: "Die..",
            qian2: "Stand der brenntechnik prüfen",
            qian1: "Überprüfe die online - funktion der anlage",
            tishi: "schließen",
            xuanqian: "Schnitt für die datenbearbeitung",
            tijiaook: "Sofort schneiden und",
            queren: "Ausrüstung offline.",
            huifu: "Nicht mit",
            lishifankui: "zurück",
            tianyijian: "Schneiden und,",
            tijiao: ":",
            fankui: ". Auf:",
            chongqian: "Zu verwende",
            qiemojilu: "Schneiden und parameter",
            chongzhijilu: "Schneiden und.",
            shengcishu: "Ausrüstung ip-adresse:",
            mimacuo: "Seriennummer des laufwerks",
            denglu: "Mit in",
            shumima: "Keine details zum equipment",
            shuzhanghu: "Die ganze",
            wangjimima: "Hinzufügen ausrüstung",
            password: "Ausrüstung liste",
            zhanghu: "Die erfolg",
            qingdenglu: "An die",
            nolianjie: "Das ist total dringend",
            shuruidshebei: "Verbindungsaufbau versucht",
            wodezhanghu: "fertig",
            xuanzejiqi: "Geben sie das wifi-passwort ein",
            moshi2: "Geben sie einen wlan namen ein",
            moshi1: "weiter",
            moshi0: "Wlan.",
            zhongzhi: "Wlan namen",
            kelu: "Lassen sie sie in der warteschleife",
            shike: "Für wlan",
            gengxintime: "Wähle die konfiguration",
            fukuan: ". Ausrüstung",
            xianwei: "Die netzwerkanlage der geräte einrichten",
            chulunbi: "modell",
            daoya: "marke",
            daosu: "Abkommen,",
            shebeixinxi: "Gilt häufig als gebrauch",
            shuaxinshuju: "strom",
            shebeihao: "ip-adresse",
            zhinengqiemo: "Die seriennummer des laufwerks",
            noshebei: "Version.",
            setdaosucuo: "Ein kluger schneidermesser",
            setdaoyacuo: "die",
            keluchucuo: "sprache",
            cutting: "",
            querenqiege: "",
            settishi: "",
            tianjiaok: "",
            setdaosu: "",
            jianchakelu: "",
            jianchazaixian: "",
            close: "",
            chulizhong: "",
            lijiqiemo: "",
            lixian: "",
            weibangdin: "",
            back: "",
            shuoming: "",
            sudu: "",
            tianjiachangyon: "",
            canshu: "",
            xiangqing: "",
            ip2: "",
            xuliehao2: "",
            shiyonzhong: "",
            zhaobudao: "",
            zhengzaisousuo: "",
            tianjiashebei: "",
            shebei: "",
            setok: "",
            startset: "",
            jiance: "",
            changshi: "",
            ok: "",
            tspassword: "",
            tishiwifiname: "",
            next: "",
            wifipassword: "",
            wifiname: "",
            quebao: "",
            peizhiwifi: "",
            peizhifangshi: "",
            sousuo: "",
            peiwang: "",
            xinhao: "",
            pinpai: "",
            xieyi: "",
            shiyoncishu: "",
            dianyuan: "",
            ip: "",
            xuliehao: "",
            banbenhao: "",
            qiemoji: "",
            sz: "",
            lang: "",
            home:'Home',
            sbpw:'Verteilungsnetz für Ausrüstung',
            wdsb:'Meine Ausrüstung',
            qrsc:'Sind Sie sicher, zu löschen?',
            sc:'Löschen',
            bc:'Erhaltung',
            wzdsb:'Gerät nicht gefunden',
            ytjsb:'Das Gerät wurde hinzugefügt',
            ycz:'Zu allgemein hinzugefügt, nicht wieder hinzufügen',
            sccg:'Löschen erfolgreich'
        },
        fra: {
            setyuyan: "Environnement linguistique",
            huanyin: "Les coupeurs intelligents sont les bienvenus",
            qssjh: "Veuillez indiquer votre numéro de téléphone portable",
            qd: "déterminer",
            qsxm: "Veuillez indiquer votre nom",
            qsrzhmm: "Entrez le mot de passe de votre compte",
            zuihousj: "Heure de la dernière mise à jour de l’équipement",
            moren: "Par défaut",
            qcz: "désurcharge",
            cishu: "À sa",
            xiugai: "modifications",
            csbzqcz: "Le nombre de coupes est insuffisant, achetez le plus rapidement possible",
            fsklwj: "Envoi du fichier gravé",
            sxz: "Mise à jour",
            sxzt: "État de mise à jour",
            user: "L’utilisation de",
            gybj: "Sur la machine",
            wxts: "Bon conseil: pour protéger vos droits et intérêts, perfectionnez vos données personnelles.",
            qsdz: "Veuillez indiquer votre adresse",
            qsyx: "Entrez votre boîte aux lettres",
            qshm: "Veuillez indiquer votre numéro de téléphone portable",
            dz: "adresse",
            yx: "La boîte aux lettres",
            phone: "Tél.",
            name: "Le nom",
            wsgrzl: "Améliorer les données à caractère personnel",
            tj: "statistiques",
            cp: "produits",
            szcsyzmm: "Pour définir les paramètres, il faut introduire un mot de passe pour valider votre autorité",
            tcdl: "Sortie de la session",
            tsms: "Entrée en mode mise en service",
            sbpz: "Configuration des équipements",
            grzl: "Données à caractère personnel",
            sycs: "Nombre de coupes restantes",
            wode: "mon",
            sp: "produits",
            jsgy: "Près de trois mois",
            jygy: "Près d’un mois",
            jqt: "Près de 7 jours",
            xl: "Volume des ventes",
            rq: "La date",
            spxl: "Volume des ventes de biens",
            mrxl: "Ventes quotidiennes",
            fenlei: "La classification",
            sksb: "Les essais ont échoué, vérifiez si la machine est correctement connectée au réseau",
            zlxd: "Les instructions sont données ci-dessous",
            cyxh: "Modèles communs",
            remenxh: "Modèles chauds",
            nownobang: "Dispositifs actuels non liés",
            lx: "off-line",
            zaixian: "En ligne",
            yilianjie: "Équipements connectés",
            sousuozhong: "Recherche d’appareils",
            czok: "Réinitialisation réussie",
            querencz: "Une réinitialisation définitive? Les informations relatives à la configuration de votre machine seront perdues",
            geshihua: "Rétablissement du réglage départ usine",
            xianweikaiguan: "Interrupteur de fin de course",
            sbbuzaixian: "Dispositif non en ligne",
            weibangshebei: "Dispositifs non liés",
            setfukuan: "FuKuan",
            setsudu: "La vitesse de",
            setcanshu: "Réglage des paramètres",
            shuzhi: "Valeurs numériques:",
            daoyaname5: "Pression du couteau 5 nom:",
            daoyaname4: "Couteaux pressés iv nom:",
            daoyaname3: "Couteaux pressés trois noms:",
            daoyaname2: "Nom de la presse de couteaux:",
            daoyaname1: "Nom de la presse à couteaux:",
            setdaoya: "Réglage de la pression du couteau",
            yzhou: "l’axe",
            xzhou: "L’axe X",
            shebeilixian: "L’équipement est hors ligne",
            nobang: "Dispositifs non liés",
            setchilunbi: "Réglage du rapport de vitesse",
            jieguo: "Résultats de la recherche",
            quxiao: "La suppression des",
            shuhao: "Entrez le mot-clé marque/modèle",
            chongqianno: "Le rechargement a échoué!",
            chongqianok: "Recharge réussie!",
            nowchong: "À payer immédiatement",
            qianxieyi: "«Accord de reconstitution»",
            tongyi: "En cliquant sur",
            qian3: "Les remboursements non justifiés ne sont pas acceptés après recharge.",
            qian2: "Fréquence des retraits d’espèces non convertibles, des retraits d’espèces ou des transferts à d’autres personnes. 2.",
            qian1: "1) le nombre d’achats peut être utilisé lors du découpage des membranes.",
            tishi: "Conseils chaleureux",
            xuanqian: "Veuillez sélectionner le montant de la recharge",
            tijiaook: "Soumission réussie",
            queren: "Confirmation de la soumission",
            huifu: "Réponse:",
            lishifankui: "Rétroaction historique",
            tianyijian: "Veuillez remplir vos observations et recommandations ici..",
            tijiao: "Présenté par le",
            fankui: "Commentaires et réactions",
            chongqian: "complément",
            qiemojilu: "Enregistrement des films coupés",
            chongzhijilu: "Dossiers complémentaires",
            shengcishu: "Fréquence résiduelle",
            mimacuo: "Le nom d’utilisateur ou le mot de passe ne sont pas corrects",
            denglu: "connexion",
            shumima: "Veuillez introduire votre mot de passe",
            shuzhanghu: "Veuillez indiquer le compte",
            wangjimima: "Oubliez votre mot de passe",
            password: "Les mots de passe",
            zhanghu: "Les comptes",
            qingdenglu: "Veuillez consulter le",
            nolianjie: "Non connecté",
            shuruidshebei: "Entrez le nom/l’identification du dispositif pour trouver le dispositif",
            wodezhanghu: "Mon compte",
            xuanzejiqi: "Sélectionnez la machine en ligne actuelle",
            moshi2: "Mode 2",
            moshi1: "Mode 1",
            moshi0: "Mode 0",
            zhongzhi: "La valeur de remplacement",
            kelu: "graver",
            shike: "A essayé",
            gengxintime: "Dernière mise à jour:",
            fukuan: "FuKuan",
            xianwei: "Fin de course",
            chulunbi: "Rapport de vitesse",
            daoya: "Couteaux à compression",
            daosu: "Couteaux à",
            shebeixinxi: "Informations relatives aux équipements",
            shuaxinshuju: "Les données à la machine",
            shebeihao: "Numéro de l’appareil",
            zhinengqiemo: "Membranes intelligentes",
            noshebei: "Aucun équipement disponible n’a pu être trouvé",
            setdaosucuo: "Couteaux vitesses d’erreur:",
            setdaoyacuo: "Erreur de réglage de la pression du couteau:",
            keluchucuo: "Graver d’erreur",
            cutting: "Film en cours de coupe",
            querenqiege: "Confirmation de la découpe",
            settishi: "Veuillez lire les couteaux à compression ou à un rythme",
            tianjiaok: "Succès de l’addition",
            setdaosu: "Réglage de la vitesse du couteau",
            jianchakelu: "L’état de graver des appareils d’inspection",
            jianchazaixian: "Contrôle en ligne",
            close: "La fermeture",
            chulizhong: "Traitement des données de découpe",
            lijiqiemo: "Coupage immédiat de la membrane",
            lixian: "Équipements hors ligne",
            weibangdin: "Non consolidé",
            back: "Le retour",
            shuoming: "Instructions pour le découpage des membranes",
            sudu: "Vitesse:",
            tianjiachangyon: "L’ajout couramment utilisés",
            canshu: "Paramètres de coupage des membranes",
            xiangqing: "Détails de membranes",
            ip2: "Pendant la période d’enquête:",
            xuliehao2: "Numéro de série du dispositif:",
            shiyonzhong: "En usage",
            zhaobudao: "L’impossibilité de trouver des informations du matériel",
            zhengzaisousuo: "recherche",
            tianjiashebei: "L’addition de matériel",
            shebei: "Liste des équipements",
            setok: "Mise en place réussie",
            startset: "Début du montage",
            jiance: "Modèles d’essai non AP",
            changshi: "Essayer de connexion",
            ok: "L’achèvement du",
            tspassword: "Veuillez vous demande votre mot de passe WiFi",
            tishiwifiname: "Veuillez indiquer le nom du wifi",
            next: "Les prochaines étapes",
            wifipassword: "Les mots de passe WiFi",
            wifiname: "Le nom du WiFi",
            quebao: "Des équipements vous connecter les points chauds",
            peizhiwifi: "La configuration du wifi",
            peizhifangshi: "Choix de la configuration",
            sousuo: "Équipement de recherche",
            peiwang: "Pour le réseau de distribution du matériel",
            xinhao: "Les modèles",
            pinpai: "La marque",
            xieyi: "Description des accords",
            shiyoncishu: "Nombre de coupe utilisés",
            dianyuan: "Alimentation électrique",
            ip: "Les adresses IP",
            xuliehao: "Les numéros de série de l’équipement",
            banbenhao: "Numéro de version",
            qiemoji: "Machines à couper la membrane intelligents",
            sz: "La mise en place",
            lang: "Langue (S)",
            home:'Home',
            sbpw:'Réseau de distribution de matériel',
            wdsb:'Mon équipement.',
            qrsc:'Vous confirmez la suppression?',
            sc:'Delete',
            bc:'Enregistrer',
            wzdsb:'Dispositif introuvable',
            ytjsb:'Ajouter le dispositif',
            ycz:'Ne pas répéter l"ajout',
            sccg:'Delete'
        },
        py: {
            setyuyan: "Настройка языка",
            huanyin: "Добр пожалова использова умн секач для рубк мембра",
            qssjh: "Пожалуйст, введ четырёхзначн номер сво мобильн",
            qd: "увер",
            qsxm: "Введите ваше имя, пожалуйста",
            qsrzhmm: "Пожалуйст, введ код на ваш счет",
            zuihousj: "Инструментар последн обновля врем",
            moren: "По умолчан",
            qcz: "Зарядка.",
            cishu: "раз",
            xiugai: "модификац",
            csbzqcz: "Чащ недостаточн, как можн скор покупк чащ",
            fsklwj: "Записа файл",
            sxz: "Обновить.",
            sxzt: "Обновить.",
            user: "использова",
            gybj: "По поводу машины.",
            wxts: "Уютн подсказк: для гарант ваш, оставьт усовершенствова профил, заб парол доступн проверк профил, вернут код!",
            qsdz: "Пожалуйста, введите ваш адрес",
            qsyx: "Пожалуйста, введите ваш почтовый ящик",
            qshm: "Пожалуйст, введ четырёхзначн номер сво мобильн",
            dz: "адрес",
            yx: "Почтов ящик",
            phone: "телефон",
            name: "им",
            wsgrzl: "Усовершенствова профил",
            tj: "статистическ",
            cp: "продукц",
            szcsyzmm: "Параметр нужн ввест парол проверк ваш доступ",
            tcdl: "Выход из системы.",
            tsms: "Переходим в режим отладки",
            sbpz: "Оборудован конфигурац",
            grzl: "Личные данные.",
            sycs: "Остаточная резка",
            wode: "мо",
            sp: "товар",
            jsgy: "Почти три месяца",
            jygy: "Почти месяц",
            jqt: "Близк 7 дне",
            xl: "продаж",
            rq: "дат",
            spxl: "Продажи.",
            mrxl: "Ежедневные продажи.",
            fenlei: "классификац",
            sksb: "Попробова выреза неудач, проверьт машин ли в порядк обьеден в сет",
            zlxd: "Попробуйте вырезать инструкцию ниже",
            cyxh: "Использ модел",
            remenxh: "Модель номер Один.",
            nownobang: "В настоящее время нет связывающего устройства",
            lx: "отключ",
            zaixian: "Онлайн -",
            yilianjie: "Уж подключа устройств",
            sousuozhong: "Оборудован поиск",
            czok: "Перезагрузка завершена.",
            querencz: "Перезагрузка? Ваш машин конфигурацион информац будут утеря",
            geshihua: "Восстановить заводские настройки",
            xianweikaiguan: "Удержива выключател",
            sbbuzaixian: "Устройство отключено.",
            weibangshebei: "Не связыва оборудован",
            setfukuan: "сукн",
            setsudu: "скорост",
            setcanshu: "Параметрический установка",
            shuzhi: "Числов:",
            daoyaname5: "Нож давлен пят назван:",
            daoyaname4: "Нож давлен четыр назван:",
            daoyaname3: "Нож давлен три назван:",
            daoyaname2: "Нож давлен два назван:",
            daoyaname1: "Нож давлен одн назван:",
            setdaoya: "Установка давления.",
            yzhou: "Вдол ос Y",
            xzhou: "Ос X",
            shebeilixian: "Устройство отключено",
            nobang: "Никакого связывающего оборудования",
            setchilunbi: "Передач чем настройк",
            jieguo: "Результаты поиска.",
            quxiao: "отмен",
            shuhao: "Пожалуйст, введ бренд/модел ключев слов",
            chongqianno: "Перезарядка не работает!",
            chongqianok: "Платежн успешн!",
            nowchong: "Немедленно.",
            qianxieyi: "Карт соглашен",
            tongyi: "Что нажм немедлен, ест вы соглас",
            qian3: "3 посл тог, как карт, не поддержива нич компенсац. Без причин",
            qian2: "2 неконвертируем наличн, снят ил возвращ.",
            qian1: "1 покупк чащ доступн для мембра когд.",
            tishi: "Хороший совет.",
            xuanqian: "Пожалуйст, выбер карт сумм",
            tijiaook: "Представлять успех",
            queren: "Подтверждаю.",
            huifu: "Ответ:",
            lishifankui: "Истор обратн связ",
            tianyijian: "Пожалуйст эт заполня ваш замечан и предложен …",
            tijiao: "представ",
            fankui: "Обратная связь мнений",
            chongqian: "карт",
            qiemojilu: "Реза мембра запис",
            chongzhijilu: "Запись зарядки",
            shengcishu: "Количеств оста",
            mimacuo: "Логин ил парол некорректн",
            denglu: "залогин",
            shumima: "Введите пароль.",
            shuzhanghu: "Пожалуйст, введ счет",
            wangjimima: "Забудь пароль.",
            password: "код",
            zhanghu: "счет",
            qingdenglu: "заход",
            nolianjie: "Не подключ",
            shuruidshebei: "Пожалуйст, устройств ввод назван/ID поиск устройств",
            wodezhanghu: "Мо счет",
            xuanzejiqi: "Выбор текущ онлайн-машин",
            moshi2: "Модел 2",
            moshi1: "Модел 1",
            moshi0: "Модел 0",
            zhongzhi: "перезагрузк",
            kelu: "записа",
            shike: "Попробова выреза",
            gengxintime: "Врем последн обновля:",
            fukuan: "сукн",
            xianwei: "удержива",
            chulunbi: "Передач чем",
            daoya: "Нож давлен",
            daosu: "Нож скорост",
            shebeixinxi: "Оборудован информац",
            shuaxinshuju: "Освеж машин Дан",
            shebeihao: "Оборудован",
            zhinengqiemo: "Интеллект реза мембра",
            noshebei: "Не мог найт доступн оборудован",
            setdaosucuo: "Настройк нож скорост пойт не так:",
            setdaoyacuo: "Настройк нож давлен пойт не так:",
            keluchucuo: "Записа пойт не так",
            cutting: "Как раз разреза мембра",
            querenqiege: "Подтверд реза",
            settishi: "Пожалуйст навед снача нож давлен ил скорост",
            tianjiaok: "Добавля успешн",
            setdaosu: "Настройк нож скорост",
            jianchakelu: "Оборудован записа состоян",
            jianchazaixian: "Оборудован онлайн-состоян",
            close: "закр",
            chulizhong: "В реза обработк Дан",
            lijiqiemo: "Немедлен реза мембра",
            lixian: "Оборудован отключ",
            weibangdin: "Не связыва",
            back: "вернут",
            shuoming: "Реза мембра инструкц",
            sudu: "Скорост:",
            tianjiachangyon: "Добав использ",
            canshu: "Реза мембра параметр",
            xiangqing: "Реза мембра подробн",
            ip2: "Оборудован ip - :",
            xuliehao2: "Оборудован серийн номер:",
            shiyonzhong: "в",
            zhaobudao: "Не мог найт оборудован информац",
            zhengzaisousuo: "обыскива",
            tianjiashebei: "Добавля оборудован",
            shebei: "Оборудован список",
            setok: "Настройк успешн",
            startset: "Начина установк",
            jiance: "Обнаруж не подключ AP модел",
            changshi: "Попробова связ",
            ok: "законч",
            tspassword: "Пожалуйст, введ код wi-fi",
            tishiwifiname: "Пожалуйст, введ wi-fi назван",
            next: "Следующий шаг.",
            wifipassword: "Wi-fi код",
            wifiname: "Wi-fi назван",
            quebao: "Чтоб ты уж даж оборудован горяч точк",
            peizhiwifi: "Конфигурац wi-fi",
            peizhifangshi: "Выбра способ конфигурац",
            sousuo: "Поисковое оборудование",
            peiwang: "Для устройств с сет",
            xinhao: "модел",
            pinpai: "бренд",
            xieyi: "Соглашен инструкц",
            shiyoncishu: "Количеств бурильн головк использова",
            dianyuan: "питан",
            ip: "IP-адрес",
            xuliehao: "Оборудован серийн номер",
            banbenhao: "Номер верс",
            qiemoji: "Интеллект секач для рубк мембра",
            sz: "настройк",
            lang: "язык",
            home:'Первая страница',
            sbpw:'сеть оборудования',
            wdsb:'мое оборудование',
            qrsc:'Подтверждение удаления?',
            sc:'Удалить',
            bc:'Сохранить',
            wzdsb:'устройство не найдено',
            ytjsb:'Добавить устройство',
            ycz:'не добавлять снова',
            sccg:'Удалено успешно'
        }
    }
}