import { AppBase } from './AppBase'

export class Language {

    static getLangValue(key){
      if(AppBase.Lang==null){
        return Language.defaultlang.chn[key];
      }else{
        var langcode = window.localStorage.getItem("langcode");
        if(langcode==""){
          return Language.defaultlang.chn[key];
        }
        var lang=null;
        lang=AppBase.Lang[langcode];
        return lang[key];
      }
    }

    static defaultlang = {
        "eng": {
            "setyuyan": "Language settings",
            "huanyin": "Welcome to Intelligent Protective Film Cutter",
            "qssjh": "Please enter your mobile number",
            "qsxm": "Please Enter user name",
            "qd": "Confirm",
            "qsrzhmm": "Please Enter  the Password",
            "zuihousj": "Device last updated time",
            "moren": "Default",
            "qcz": "To recharge",
            "cishu": "Cutting Times",
            "xiugai": "Modify",
            "csbzqcz": "Insufficient cutting times, please recharge",
            "fsklwj": "Send cut file",
            "sxz": "Refreshing",
            "sxzt": "Refresh Status",
            "user": "Use",
            "gybj": "About this cutter",
            "wxts": "Tips: To protect your rights and interests, please complete your personal information. If you forget your password, you can verify your personal information and retrieve your password!",
            "qsdz": "Please Enter Your Address",
            "qsyx": "Please enter your email",
            "qshm": "Please enter your mobile number",
            "dz": "address",
            "yx": "Email",
            "phone": "Tel. No.",
            "name": "Full name",
            "wsgrzl": "Improve your personal information",
            "tj": "Statistics",
            "cp": "product",
            "sy": "Homepage",
            "szcsyzmm": "Setting parameters requires a password to verify your permissions",
            "tcdl": "Logout",
            "tsms": "Enter debug mode",
            "sbpz": "Device Configuration",
            "grzl": "personal data",
            "sycs": "Remaining cutting times",
            "wode": "My",
            "sp": "commodity",
            "jsgy": "Last 3 months",
            "jygy": "Last 1 months",
            "jqt": "Last 7 days",
            "xl": "Sales volume",
            "rq": "date",
            "spxl": "Commodity sales volume",
            "mrxl": "Daily sales volume",
            "fenlei": "classification",
            "sksb": "Test cutting failed, please check if the machine  is connected to the network normally",
            "zlxd": "Test cutting",
            "cyxh": "Common models",
            "remenxh": "Popular models",
            "nownobang": "No devices are currently bound",
            "lx": "Off-line",
            "zaixian": "On-line",
            "yilianjie": "Device is Connected",
            "sousuozhong": "Device searching",
            "czok": "Reset succeeded",
            "querencz": "Are you sure to reset? Current configuration of device will be removed",
            "geshihua": "Restore factory settings",
            "xianweikaiguan": "Limit switch",
            "sbbuzaixian": "Device is offline",
            "weibangshebei": "Unbound to device",
            "setfukuan": "Cutting Width",
            "setsudu": "Speed",
            "setcanshu": "Parameter setting",
            "shuzhi": "Value",
            "daoyaname5": "Cutting Pressure 5",
            "daoyaname4": "Cutting Pressure 4",
            "daoyaname3": "Cutting Pressure 3",
            "daoyaname2": "Cutting Pressure 2",
            "daoyaname1": "Cutting Pressure 1",
            "setdaoya": "Cutting Pressure setting",
            "yzhou": "Y axis",
            "xzhou": "X axis",
            "shebeilixian": "Device is offline",
            "nobang": "Unbound to device",
            "setchilunbi": "Scale setting",
            "jieguo": "search result",
            "quxiao": "cancel",
            "shuhao": "Please enter brand / model keywords",
            "chongqianno": "Recharge failed",
            "chongqianok": "Recharge succeeded!",
            "nowchong": "Pay Now",
            "qianxieyi": "Recharge agreement",
            "tongyi": "Click Pay Now represents that you are agree to the payment agreement terms.",
            "qian3": "3. After recharging, no refund!",
            "qian2": "2. The number of cutting times cannot be exchanged for cash, withdrawn or transferred to others.",
            "qian1": "1. The purchase times can be used for film cutting.",
            "tishi": "Tips",
            "xuanqian": "Please select the recharge amount",
            "tijiaook": "Submit successfully",
            "queren": "Confirm submission",
            "huifu": "Reply",
            "lishifankui": "History Feedback",
            "tianyijian": "Please fill in your comments and suggestions here",
            "tijiao": "Submit",
            "fankui": "Feedback",
            "chongqian": "Recharge",
            "qiemojilu": "Cutting record",
            "chongzhijilu": "Recharge record",
            "shengcishu": "Remaining times",
            "mimacuo": "Username or password is incorrect",
            "denglu": "Login",
            "shumima": "Please enter the password",
            "shuzhanghu": "Please enter account name",
            "wangjimima": "Forget password",
            "password": "Password",
            "zhanghu": "account",
            "qingdenglu": "Please login",
            "nolianjie": "Unconnected",
            "shuruidshebei": "Please enter the device name / ID to find the device",
            "wodezhanghu": "My account",
            "xuanzejiqi": "Select the current online machine",
            "moshi2": "Mode 2",
            "moshi1": "Mode 1",
            "moshi0": "Mode 0",
            "zhongzhi": "Reset",
            "kelu": "Cut",
            "shike": "Test Cutting",
            "gengxintime": "Last update time",
            "xianwei": "Limit",
            "fukuan": "Width of Cutting",
            "chulunbi": "Scale",
            "daoya": "Knife pressure",
            "shebeixinxi": "Device information",
            "daosu": "Cutting speed",
            "shuaxinshuju": "Refresh machine data",
            "shebeihao": "Device number",
            "zhinengqiemo": "Intelligent film cutting",
            "noshebei": "No available devices is found",
            "setdaosucuo": "tool speed setting Error",
            "setdaoyacuo": "tool pressure setting Error",
            "keluchucuo": "Cutting Error",
            "cutting": "Film Cutting",
            "querenqiege": "Confirm cutting",
            "settishi": "Please set the tool pressure and speed first",
            "tianjiaok": "Added successfully",
            "setdaosu": "Set cutting speed",
            "jianchakelu": "Check the cutting status of the device",
            "jianchazaixian": "Check device online status",
            "close": "Close",
            "chulizhong": "Cutting data processing",
            "lijiqiemo": "Cut Now",
            "lixian": "Device is offline",
            "weibangdin": "Unbound",
            "back": "Return",
            "shuoming": "cutting instructions",
            "sudu": "Speed:",
            "tianjiachangyon": "Add as common",
            "canshu": "Cutting parameters",
            "xiangqing": "Details of cutting",
            "ip2": "Device IP:",
            "xuliehao2": "Device serial number:",
            "shiyonzhong": "in use",
            "zhaobudao": "No device found",
            "zhengzaisousuo": "Searching",
            "tianjiashebei": "Add device",
            "shebei": "Device list",
            "setok": "Set up successfully",
            "startset": "Set up",
            "jiance": "Detect unconnected AP mode",
            "changshi": "Try to connect",
            "ok": "Complete",
            "tspassword": "Please enter WiFi password",
            "tishiwifiname": "Please enter WiFi name",
            "next": "Next step",
            "wifipassword": "Wifi password",
            "wifiname": "WiFi name",
            "quebao": "Make sure already connected with device  hotspot",
            "peizhiwifi": "Configure WiFi",
            "peizhifangshi": "Select configuration mode",
            "sousuo": "Search device",
            "peiwang": "Set WiFi for device",
            "xinhao": "Model",
            "pinpai": "Brand",
            "xieyi": "Agreement description",
            "shiyoncishu": "Using time for blades",
            "dianyuan": "Power Supply",
            "ip": "IP address",
            "xuliehao": "Device serial number",
            "banbenhao": "Version number",
            "qiemoji": "Intelligent Protective Film Cutter",
            "sz": "Set up",
            "lang": "Language",
            "authlogin": "Authorized login",
            "emailnoreg": "Email is not registered",
            "mobilenoreg": "Mobile number is not registered",
            "resetsuccess": "Reset successfully, please log in again",
            "diffpassword": "The password entered is different",
            "loginnameempty": "Username is empty, please enter again!",
            "loginnameisused": "The username is already used, please fill in again!",
            "registrysuccess": "Registered successfully",
            "passwordshort": "Password is less than 6 characters, please re-enter password",
            "verifyincorrect": "Verification code  error, please try again",
            "emailuse": "Email has been used",
            "mobileuse": "Mobile number has been used",
            "mobilenouseincorrect": "Mobile phone number is wrong, please re-enter!",
            "sendverifycodefail": "Failed to send verification code,please try again later",
            "verifycodesent": "Verification code has been sent, please check it",
            "noqrcode": "No QR code",
            "forgetemail": "Modify email",
            "forgetphone": "Modify mobile phone number",
            "emailyanzhengma": "Please log in email to get the verification code and enter",
            "editingemail": "Email",
            "enteremail": "Please enter your email",
            "register": "Register",
            "resetyanzhengma": "Resend",
            "sendyanzhengma": "",
            "getyanzhengma": "Get verification code",
            "enteryanzhengma": "Please enter verification code",
            "yanzhengma": "Verification code",
            "enterphone": "Please enter mobile number",
            "editingphone": "Mobile number",
            "passwordlen": "Please enter the password",
            "entername": "Please enter username",
            "editingname": "Username",
            "emailregister": "Register with Email",
            "phoneregister": "Register with mobile number",
            "xinyonhuzhuce": "Register",
            "amount": "Amount",
            "scanpay": "Please use wechat to pay!",
            "loadmore": "Load more",
            "quicksearch": "Hot search",
            "wifipermission": "Please allow reading wifi and turn on wifi in app permissions",
            "selectwifi": "Choose WiFi",
            "cutfail": "File upload failed",
            "downloadfail": "File download failed",
            "setpressurefail": "Failed to set cutting force",
            "setspeedfail": "Failed to set speed",
            "app_name": "CloudCutter",
            "paymentsuccess": "Pay succeeded",
            "confirmrecharge": "Whether to confirm the recharge",
            "search": "Search",
            "qr": "Confirm",
            "qrtcdl": "Confirm log-out?",
            "home": "Home",
            "sbpw": "Set Wifi",
            "wdsb": "My device",
            "qrsc": "Confirm delete?",
            "sc": "Delete",
            "bc": "Save",
            "wzdsb": "No device found",
            "ytjsb": "The device has been added",
            "ycz": "Added to common list, please don''t add repeatedly",
            "sccg": "Delete successfully",
            "jqzt": "Machine OK, idle",
            "klz":"In operation",
            "exitapp":"Back again will exit app",
            "nonetwork":"Please check your network"
          },
          "chn": {
            "setyuyan": "语言设置",
            "huanyin": "欢迎使用智能切膜机",
            "qssjh": "请输入您的手机号码",
            "qsxm": "请输入您的用户名",
            "qd": "确定",
            "qsrzhmm": "请输入您的账户密码",
            "zuihousj": "设备最后更新时间",
            "moren": "默认",
            "qcz": "去充值",
            "cishu": "可切割次数",
            "xiugai": "修改",
            "csbzqcz": "切割次数不足,请尽快购买次数",
            "fsklwj": "发送切割文件",
            "sxz": "刷新中",
            "sxzt": "刷新状态",
            "user": "使用",
            "gybj": "关于本机",
            "wxts": "温馨提示：为保障您的权益，请完善个人资料，忘记密码时可通过验证个人资料，找回密码！",
            "qsdz": "请输入您的地址",
            "qsyx": "请输入您的邮箱",
            "qshm": "请输入您的手机号码",
            "dz": "地址",
            "yx": "邮箱",
            "phone": "电话",
            "name": "姓名",
            "wsgrzl": "完善个人资料",
            "tj": "统计",
            "cp": "产品",
            "sy": "首页",
            "szcsyzmm": "设置参数请输入密码",
            "tcdl": "退出登录",
            "tsms": "进入调试模式",
            "sbpz": "设备配置",
            "grzl": "个人资料",
            "sycs": "剩余切割次数",
            "wode": "我的",
            "sp": "商品",
            "jsgy": "近3个月",
            "jygy": "近1个月",
            "jqt": "近7天",
            "xl": "销量",
            "rq": "日期",
            "spxl": "商品销量",
            "mrxl": "每日销量",
            "fenlei": "分类",
            "sksb": "试刻失败，请查看机器是否正常联网",
            "zlxd": "试刻指令已下达",
            "cyxh": "常用型号",
            "remenxh": "热门型号",
            "nownobang": "当前无绑定设备",
            "lx": "离线",
            "zaixian": "在线",
            "yilianjie": "已连接设备",
            "sousuozhong": "设备搜索中",
            "czok": "重置成功",
            "querencz": "确定重置？        您的机器的配置信息将丢失",
            "geshihua": "恢复出厂设置",
            "xianweikaiguan": "限位开关",
            "sbbuzaixian": "设备不在线",
            "weibangshebei": "未绑定设备",
            "setfukuan": "幅宽",
            "setsudu": "速度",
            "setcanshu": "参数设置",
            "shuzhi": "数值",
            "daoyaname5": "刀压五名称：",
            "daoyaname4": "刀压四名称：",
            "daoyaname3": "刀压三名称：",
            "daoyaname2": "刀压二名称：",
            "daoyaname1": "刀压一名称：",
            "setdaoya": "刀压设置",
            "yzhou": "Y轴",
            "xzhou": "X轴",
            "shebeilixian": "设备已离线",
            "nobang": "无绑定设备",
            "setchilunbi": "齿轮比设置",
            "jieguo": "搜索结果",
            "quxiao": "取消",
            "shuhao": "请输入品牌/型号关键词",
            "chongqianno": "充值失败!",
            "chongqianok": "充值成功!",
            "nowchong": "立即支付",
            "qianxieyi": "《充值协议》",
            "tongyi": "点击立即支付，即表示您已经同意",
            "qian3": "3.充值后，不支持无理由退款。",
            "qian2": "2.次数不可兑换现金、提现或转赠他人。",
            "qian1": "1.购买次数可用于切膜时使用。",
            "tishi": "温馨提示",
            "xuanqian": "请选择充值金额",
            "tijiaook": "提交成功",
            "queren": "确认提交",
            "huifu": "回复：",
            "lishifankui": "历史反馈",
            "tianyijian": "请在此填写您的意见和建议…",
            "tijiao": "提交",
            "fankui": "意见反馈",
            "chongqian": "充值",
            "qiemojilu": "切膜记录",
            "chongzhijilu": "充值记录",
            "shengcishu": "剩余次数",
            "mimacuo": "用户名或密码不正确",
            "denglu": "登录",
            "shumima": "请输入密码",
            "shuzhanghu": "请输入账户",
            "wangjimima": "忘记密码",
            "password": "密码",
            "zhanghu": "账户",
            "qingdenglu": "请登录",
            "nolianjie": "未连接",
            "shuruidshebei": "请输入设备名称/ID查找设备",
            "wodezhanghu": "我的账户",
            "xuanzejiqi": "选择当前在线机器",
            "moshi2": "模式2",
            "moshi1": "模式1",
            "moshi0": "模式0",
            "zhongzhi": "重置",
            "kelu": "切割",
            "shike": "试刻",
            "gengxintime": "最后更新时间：",
            "xianwei": "限位",
            "fukuan": "幅宽",
            "chulunbi": "齿轮比",
            "daoya": "刀压",
            "shebeixinxi": "设备信息",
            "daosu": "切割速度",
            "shuaxinshuju": "刷新机器数据",
            "shebeihao": "设备号",
            "zhinengqiemo": "智能切膜",
            "noshebei": "找不到可用设备",
            "setdaosucuo": "设置刀速出错：",
            "setdaoyacuo": "设置刀压出错：",
            "keluchucuo": "切割出错",
            "cutting": "正在切膜",
            "querenqiege": "确认切割",
            "settishi": "请先设置刀压或者速度",
            "tianjiaok": "添加成功",
            "setdaosu": "设置刀速",
            "jianchakelu": "检查设备切割状态",
            "jianchazaixian": "检查设备在线状态",
            "close": "关闭",
            "chulizhong": "切割数据处理中",
            "lijiqiemo": "立即切膜",
            "lixian": "设备离线",
            "weibangdin": "未绑定",
            "back": "返回",
            "shuoming": "切膜说明",
            "sudu": "速度：",
            "tianjiachangyon": "添加为常用",
            "canshu": "切膜参数",
            "xiangqing": "切膜详情",
            "ip2": "设备ip：",
            "xuliehao2": "设备序列号：",
            "shiyonzhong": "使用中",
            "zhaobudao": "找不到设备",
            "zhengzaisousuo": "正在搜索",
            "tianjiashebei": "添加设备",
            "shebei": "设备列表",
            "setok": "设置成功",
            "startset": "开始设置",
            "jiance": "检测未连接AP模式",
            "changshi": "尝试连接",
            "ok": "完成",
            "tspassword": "请输入WiFi密码",
            "tishiwifiname": "请输入wifi名称",
            "next": "下一步",
            "wifipassword": "WiFi密码",
            "wifiname": "WiFi名称",
            "quebao": "确保你已经连上设备热点",
            "peizhiwifi": "配置wifi",
            "peizhifangshi": "选择配置方式",
            "sousuo": "搜索设备",
            "peiwang": "为设备进行配网",
            "xinhao": "型号",
            "pinpai": "品牌",
            "xieyi": "协议说明",
            "shiyoncishu": "刀头使用次数",
            "dianyuan": "电源",
            "ip": "IP地址",
            "xuliehao": "设备序列号",
            "banbenhao": "设备版本号",
            "qiemoji": "智能切膜机",
            "sz": "设置",
            "lang": "语言",
            "authlogin": "授权登录",
            "emailnoreg": "邮箱没有被注册",
            "mobilenoreg": "手机号码没有注册",
            "resetsuccess": "重设成功，请重新登录",
            "diffpassword": "两次输入的密码不一样",
            "loginnameempty": "用户名为空，请重新填写！",
            "loginnameisused": "用户名已经被使用，请重新填写！",
            "registrysuccess": "注册成功",
            "passwordshort": "密码少于6位，请重新输入密码",
            "verifyincorrect": "验证码校验失败，请重新尝试",
            "emailuse": "邮件已经被使用",
            "mobileuse": "手机号码已经被使用",
            "mobilenouseincorrect": "手机号码错误，请重新输入！",
            "sendverifycodefail": "验证码发送失败，请稍后重试",
            "verifycodesent": "验证码已发送，请注意查收",
            "noqrcode": "没有二维码",
            "forgetemail": "邮箱修改",
            "forgetphone": "手机号码修改",
            "emailyanzhengma": "请登录邮箱获取验证码并输入",
            "editingemail": "邮箱",
            "enteremail": "请输入邮箱",
            "register": "注册",
            "resetyanzhengma": "重新发送",
            "sendyanzhengma": "秒后重新发送",
            "getyanzhengma": "获取验证码",
            "enteryanzhengma": "请输入验证码",
            "yanzhengma": "验证码",
            "enterphone": "请输入手机号码",
            "editingphone": "手机号码",
            "passwordlen": "请输入密码",
            "entername": "请输入用户名",
            "editingname": "用户名",
            "emailregister": "邮箱注册",
            "phoneregister": "手机号码注册",
            "xinyonhuzhuce": "新用户注册",
            "amount": "金额",
            "scanpay": "请使用微信支付",
            "loadmore": "加载更多",
            "quicksearch": "快捷搜索",
            "wifipermission": "请在应用权限中允许读取wifi并打开wifi",
            "selectwifi": "选择wifi",
            "cutfail": "上传文件失败",
            "downloadfail": "文件下载失败",
            "setpressurefail": "设置刀压失败",
            "setspeedfail": "设置速度失败",
            "app_name": "CloudCutter",
            "paymentsuccess": "支付成功",
            "confirmrecharge": "是否确认充值",
            "search": "搜索",
            "qr": "确认",
            "qrtcdl": "确定退出账号吗？",
            "home": "首页",
            "sbpw": "设备配网",
            "wdsb": "我的设备",
            "qrsc": "确认删除吗？",
            "sc": "删除",
            "bc": "保存",
            "wzdsb": "未找到设备",
            "ytjsb": "已添加该设备",
            "ycz": "已添加至常用，请勿重复添加",
            "sccg": "删除成功",
            "jqzt": "机器正常，空闲状态",
            "klz":"刻绘进行中",
            "xitong":'系统参数',
            "exitapp":"再点一次将退出程序",
            "nonetwork":"当前网络异常，请检查网络"
          },
          "esp": {
            "setyuyan": "ajustes de idioma",
            "huanyin": "Bienvenido a Intelligent Protective Film Cutter",
            "qssjh": "Por favor, introduzca su número de móvil",
            "qsxm": "por favor ingrese el nombre de usuario",
            "qd": "Confirmar",
            "qsrzhmm": "Por favor introduzca la contraseña",
            "zuihousj": "Hora de la última actualización del dispositivo",
            "moren": "Defecto",
            "qcz": "Recargar",
            "cishu": "Tiempos de corte",
            "xiugai": "Modificar",
            "csbzqcz": "Tiempos de corte insuficientes, recargue",
            "fsklwj": "Enviar archivo cortado",
            "sxz": "Refrescante",
            "sxzt": "Actualizar estado",
            "user": "Utilizar",
            "gybj": "Acerca de esta máquina",
            "wxts": "Consejos: para proteger sus derechos e intereses, complete su información personal. Si olvida su contraseña, puede verificar su información personal y recuperar su contraseña.",
            "qsdz": "Por favor, introduzca su dirección",
            "qsyx": "Por favor introduzca su correo electrónico",
            "qshm": "Por favor, introduzca su número de móvil",
            "dz": "Dirección",
            "yx": "Email",
            "phone": "número de teléfono",
            "name": "nombre completo",
            "wsgrzl": "Mejora tu información personal",
            "tj": "Estadísticas",
            "cp": "producto",
            "sy": "Página principal",
            "szcsyzmm": "Establecer parámetros requiere una contraseña para verificar sus permisos",
            "tcdl": "Cerrar sesión",
            "tsms": "Ingrese al modo de depuración",
            "sbpz": "Configuración del dispositivo",
            "grzl": "Información personal",
            "sycs": "Tiempos de corte restantes",
            "wode": "mi",
            "sp": "mercancía",
            "jsgy": "Últimos 3 meses",
            "jygy": "Últimos 1 meses",
            "jqt": "Últimos 7 días",
            "xl": "volumen de ventas",
            "rq": "fecha",
            "spxl": "Volumen de ventas de productos",
            "mrxl": "Volumen diario de ventas",
            "fenlei": "clasificación",
            "sksb": "Error en el corte de prueba, compruebe si la máquina está conectada a la red normalmente",
            "zlxd": "Prueba de corte",
            "cyxh": "Modelos comunes",
            "remenxh": "Modelos populares",
            "nownobang": "Actualmente no hay dispositivos vinculados",
            "lx": "Desconectado",
            "zaixian": "En línea",
            "yilianjie": "El dispositivo está conectado",
            "sousuozhong": "Dispositivo de búsqueda",
            "czok": "Reinicio exitoso",
            "querencz": "Estás seguro de reiniciar? Se eliminará la configuración actual del dispositivo",
            "geshihua": "Restaurar la configuración de fábrica",
            "xianweikaiguan": "Límite de cambio",
            "sbbuzaixian": "El dispositivo esta desconectado",
            "weibangshebei": "Sin consolidar al dispositivo",
            "setfukuan": "Ancho de corte",
            "setsudu": "Velocidad",
            "setcanshu": "Ajustes de parámetros",
            "shuzhi": "Valor",
            "daoyaname5": "Presion De Corte 5",
            "daoyaname4": "Presion De Corte 4",
            "daoyaname3": "Presion De Corte 3",
            "daoyaname2": "Presion De Corte 2",
            "daoyaname1": "Presion De Corte 1",
            "setdaoya": "Ajuste de fuerza de corte",
            "yzhou": "Eje Y",
            "xzhou": "Eje X",
            "shebeilixian": "El dispositivo esta desconectado",
            "nobang": "Sin consolidar al dispositivo",
            "setchilunbi": "Ajuste de escala",
            "jieguo": "Resultados de la búsqueda",
            "quxiao": "cancelación",
            "shuhao": "Ingrese palabras clave de marca / modelo",
            "chongqianno": "Fallo de recarga",
            "chongqianok": "¡Recarga exitosa!",
            "nowchong": "Pagar ahora",
            "qianxieyi": "Acuerdo de recarga",
            "tongyi": "Haga clic en Pagar ahora representa que está de acuerdo con los términos del acuerdo de pago.",
            "qian3": "3.¡Después de recargar, no hay reembolso!",
            "qian2": "2.El número de tiempos de corte no puede cambiarse por efectivo, retirarse o transferirse a otros.",
            "qian1": "1. el número de compras se puede utilizar para cortar la membrana.",
            "tishi": "Consejos",
            "xuanqian": "Por favor seleccione la cantidad de recarga",
            "tijiaook": "Enviar con éxito",
            "queren": "Confirmar envío",
            "huifu": "Respuesta:",
            "lishifankui": "Comentarios sobre la historia",
            "tianyijian": "Por favor complete sus comentarios y sugerencias aquí",
            "tijiao": "Enviar",
            "fankui": "comentarios",
            "chongqian": "Recargar",
            "qiemojilu": "Registro de corte",
            "chongzhijilu": "Registro de recarga",
            "shengcishu": "Restante Veces",
            "mimacuo": "El nombre de usuario o la contraseña no son correctos",
            "denglu": "Iniciar sesión",
            "shumima": "Por favor, introduzca su contraseña",
            "shuzhanghu": "Por favor ingrese su cuenta",
            "wangjimima": "Olvidé mi contraseña",
            "password": "La contraseña",
            "zhanghu": "Las cuentas",
            "qingdenglu": "Por favor Iniciar sesión",
            "nolianjie": "Desconectado",
            "shuruidshebei": "Ingrese el nombre / ID del dispositivo para encontrar el dispositivo",
            "wodezhanghu": "Mi cuenta",
            "xuanzejiqi": "Seleccione la máquina en línea actual",
            "moshi2": "Modo 2",
            "moshi1": "Modo 1",
            "moshi0": "Modo 0",
            "zhongzhi": "Reiniciar",
            "kelu": "Cortar",
            "shike": "Prueba de corte",
            "gengxintime": "Última hora de actualización",
            "xianwei": "Límite",
            "fukuan": "Ancho de corte",
            "chulunbi": "Escala",
            "daoya": "Presión de cuchillo",
            "shebeixinxi": "Información del dispositivo",
            "daosu": "Velocidade de corte",
            "shuaxinshuju": "Actualizar datos de la máquina",
            "shebeihao": "Número de dispositivo",
            "zhinengqiemo": "Corte de película inteligente",
            "noshebei": "No se encontraron dispositivos disponibles.",
            "setdaosucuo": "Error de ajuste de velocidad de herramienta",
            "setdaoyacuo": "Error de ajuste de presión de la herramienta",
            "keluchucuo": "Error de corte",
            "cutting": "Corte de película",
            "querenqiege": "Confirmar el corte",
            "settishi": "Primero configure la presión y la velocidad de la herramienta",
            "tianjiaok": "Agregado exitosamente",
            "setdaosu": "Establecer velocidad de corte",
            "jianchakelu": "Compruebe el estado de corte del dispositivo.",
            "jianchazaixian": "Verificar el estado en línea del dispositivo",
            "close": "Cerca",
            "chulizhong": "Corte de procesamiento de datos",
            "lijiqiemo": "Cortar ahora",
            "lixian": "El dispositivo esta desconectado",
            "weibangdin": "Sin consolidar",
            "back": "Regreso",
            "shuoming": "instrucciones de corte",
            "sudu": "Velocidad",
            "tianjiachangyon": "Agregar como común",
            "canshu": "Parámetros de corte",
            "xiangqing": "Detalles de corte",
            "ip2": "IP del dispositivo:",
            "xuliehao2": "Idear número de serie:",
            "shiyonzhong": "en uso",
            "zhaobudao": "Ningún dispositivo encontrado",
            "zhengzaisousuo": "buscando",
            "tianjiashebei": "Añadir dispositivo",
            "shebei": "Lista de dispositivos",
            "setok": "Configurar con éxito",
            "startset": "Preparar",
            "jiance": "Detecta el modo AP desconectado",
            "changshi": "Intenta conectarte",
            "ok": "Completa",
            "tspassword": "Por favor ingrese la contraseña de WiFi",
            "tishiwifiname": "Por favor ingrese el nombre de WiFi",
            "next": "Próximo paso",
            "wifipassword": "Contraseña de wifi",
            "wifiname": "Nombre de WiFi",
            "quebao": "Asegúrese de que ya esté conectado con el punto de acceso del dispositivo",
            "peizhiwifi": "Configurar WiFi",
            "peizhifangshi": "Seleccionar modo de configuración",
            "sousuo": "Dispositivo de búsqueda",
            "peiwang": "Establecer WiFi para dispositivo",
            "xinhao": "Modelo",
            "pinpai": "Marca",
            "xieyi": "Descripción del acuerdo",
            "shiyoncishu": "Usando tiempo para cuchillas",
            "dianyuan": "Fuente de alimentación",
            "ip": "dirección IP",
            "xuliehao": "Número de serie del dispositivo",
            "banbenhao": "Número de versión",
            "qiemoji": "Cortador de película protectora inteligente",
            "sz": "Preparar",
            "lang": "Idioma",
            "authlogin": "Inicio de sesión autorizado",
            "emailnoreg": "El correo electrónico no está registrado",
            "mobilenoreg": "El número de móvil no está registrado.",
            "resetsuccess": "Restablezca correctamente, inicie sesión nuevamente",
            "diffpassword": "La contraseña ingresada es diferente",
            "loginnameempty": "El nombre de usuario está vacío, ingrese nuevamente.",
            "loginnameisused": "El nombre de usuario ya está en uso. ¡Rellene de nuevo!",
            "registrysuccess": "Registrado correctamente",
            "passwordshort": "La contraseña tiene menos de 6 caracteres, vuelva a ingresar la contraseña",
            "verifyincorrect": "Error de código de verificación, por favor intente nuevamente",
            "emailuse": "El correo electrónico ha sido usado",
            "mobileuse": "Se ha utilizado el número de móvil.",
            "mobilenouseincorrect": "El número de teléfono móvil es incorrecto, vuelva a ingresar.",
            "sendverifycodefail": "No se pudo enviar el código de verificación. Vuelve a intentarlo más tarde.",
            "verifycodesent": "Se ha enviado el código de verificación, verifíquelo",
            "noqrcode": "Sin código QR",
            "forgetemail": "Modificar correo electrónico",
            "forgetphone": "Modificar número de teléfono móvil",
            "emailyanzhengma": "Inicie sesión en el correo electrónico para obtener el código de verificación e ingrese",
            "editingemail": "Email",
            "enteremail": "Por favor introduzca su correo electrónico",
            "register": "Registrarse",
            "resetyanzhengma": "Reenviar",
            "sendyanzhengma": "",
            "getyanzhengma": "Obtén el código de verificación",
            "enteryanzhengma": "Por favor ingrese el código de verificación",
            "yanzhengma": "Código de verificación",
            "enterphone": "Por favor, introduzca el número de móvil",
            "editingphone": "Número de teléfono móvil",
            "passwordlen": "Por favor introduzca la contraseña",
            "entername": "Por favor ingrese nombre de usuario",
            "editingname": "Nombre de usuario",
            "emailregister": "Registrarse con correo electrónico",
            "phoneregister": "Registrarse con número de móvil",
            "xinyonhuzhuce": "Registrarse",
            "amount": "Cantidad",
            "scanpay": "Utiliza wechat para pagar!",
            "loadmore": "Carga más",
            "quicksearch": "Busqueda rapida",
            "wifipermission": "Permita la lectura de wifi y active wifi en los permisos de la aplicación",
            "selectwifi": "Elige wifi",
            "cutfail": "Error al cargar el archivo",
            "downloadfail": "Descarga de archivo fallida",
            "setpressurefail": "Error al establecer la fuerza de corte",
            "setspeedfail": "No se pudo establecer la velocidad",
            "app_name": "CloudCutter",
            "paymentsuccess": "Pago exitoso",
            "confirmrecharge": "Ya sea para confirmar la recarga",
            "search": "Buscar",
            "qr": "Confirmar",
            "qrtcdl": "Seguro para cerrar sesión?",
            "home": "Inicio",
            "sbpw": "Establecer WiFi",
            "wdsb": "Mi dispositivo",
            "qrsc": "Confirmar eliminación?",
            "sc": "Eliminar",
            "bc": "Salvar",
            "wzdsb": "Ningún dispositivo encontrado",
            "ytjsb": "El dispositivo ha sido agregado",
            "ycz": "Agregado a la lista común, no agregue repetidamente",
            "sccg": "Eliminar con éxito",
            "jqzt": "La máquina está libre.",
            "klz":"En marcha",
            "exitapp":"Back again will exit app",
            "nonetwork":"Please check your network"
          },
          "por": {
            "setyuyan": "opções de linguagem",
            "huanyin": "Bem-vindo ao cortador de filme protetor inteligente",
            "qssjh": "Por favor, insira seu número de telefone",
            "qsxm": "digite o nome do usuário",
            "qd": "confirme",
            "qsrzhmm": "Por favor insira a senha",
            "zuihousj": "Hora da última atualização do dispositivo",
            "moren": "Padrão",
            "qcz": "Recarregar",
            "cishu": "Tempos de corte",
            "xiugai": "Modificar",
            "csbzqcz": "Tempos de corte insuficientes, recarregue",
            "fsklwj": "Enviar arquivo cortado",
            "sxz": "Refrescante",
            "sxzt": "Atualizar status",
            "user": "Usar",
            "gybj": "Sobre esta máquina",
            "wxts": "Dicas: Para proteger seus direitos e interesses, preencha suas informações pessoais. Se você esquecer sua senha, poderá verificar suas informações pessoais e recuperar sua senha!",
            "qsdz": "Digite seu endereço",
            "qsyx": "Por favor introduza o seu e-mail",
            "qshm": "Por favor, insira seu número de telefone",
            "dz": "endereço",
            "yx": "O email",
            "phone": "número de telefone",
            "name": "nome completo",
            "wsgrzl": "Melhore suas informações pessoais",
            "tj": "Estatisticas",
            "cp": "produtos",
            "sy": "Pagina inicial",
            "szcsyzmm": "A configuração de parâmetros requer uma senha para verificar suas permissões",
            "tcdl": "Sair",
            "tsms": "Entre no modo de depuração",
            "sbpz": "Configuração do dispositivo",
            "grzl": "Dados pessoais",
            "sycs": "Tempos de corte restantes",
            "wode": "meu",
            "sp": "mercadoria",
            "jsgy": "Últimos 3 meses",
            "jygy": "Últimos 1 meses",
            "jqt": "Últimos 7 dias",
            "xl": "volume de vendas",
            "rq": "data",
            "spxl": "Volume de vendas de commodities",
            "mrxl": "Volume diário de vendas",
            "fenlei": "classificação",
            "sksb": "O corte do teste falhou, verifique se a máquina está conectada à rede normalmente",
            "zlxd": "Teste de corte",
            "cyxh": "Modelos comuns",
            "remenxh": "Modelos populares",
            "nownobang": "No momento, nenhum dispositivo está vinculado",
            "lx": "Desligado",
            "zaixian": "On-line",
            "yilianjie": "O dispositivo está conectado",
            "sousuozhong": "Pesquisa de dispositivos",
            "czok": "Reposição concluída",
            "querencz": "Você tem certeza de que redefiniu? A configuração atual do dispositivo será removida",
            "geshihua": "Restaurar configurações de fábrica",
            "xianweikaiguan": "Interruptor de limite",
            "sbbuzaixian": "O dispositivo está offline",
            "weibangshebei": "Não vinculado ao dispositivo",
            "setfukuan": "Largura de corte",
            "setsudu": "Rapidez",
            "setcanshu": "Configurações de parâmetros",
            "shuzhi": "Valor",
            "daoyaname5": "Pressão De Corte 5",
            "daoyaname4": "Pressão De Corte 4",
            "daoyaname3": "Pressão De Corte 3",
            "daoyaname2": "Pressão De Corte 2",
            "daoyaname1": "Pressão De Corte 1",
            "setdaoya": "Ajuste da força de corte",
            "yzhou": "Eixo Y",
            "xzhou": "Eixo X",
            "shebeilixian": "O dispositivo está offline",
            "nobang": "Não vinculado ao dispositivo",
            "setchilunbi": "Configuração de escala",
            "jieguo": "Resultados da pesquisa",
            "quxiao": "cancelar",
            "shuhao": "Insira palavras-chave de marca / modelo",
            "chongqianno": "Recarga falhada!",
            "chongqianok": "Recarga realizada",
            "nowchong": "Pague agora",
            "qianxieyi": "Contrato de recarga",
            "tongyi": "O clique em Pagar agora representa que você concorda com os termos do contrato de pagamento.",
            "qian3": "3.Após a recarga, não há reembolso!",
            "qian2": "2 O número de tempos de corte não pode ser trocado por dinheiro, retirado ou transferido para outras pessoas.",
            "qian1": "1. o número de compras pode ser usado durante o corte de membrana.",
            "tishi": "Dicas",
            "xuanqian": "Por favor, selecione o valor da recarga",
            "tijiaook": "Enviar com sucesso",
            "queren": "Confirmar envio",
            "huifu": "Resposta:",
            "lishifankui": "Comentários sobre o histórico",
            "tianyijian": "Por favor, preencha seus comentários e sugestões aqui",
            "tijiao": "Enviar",
            "fankui": "Comentários",
            "chongqian": "Recarrega",
            "qiemojilu": "Registro de corte",
            "chongzhijilu": "Recarregar registro",
            "shengcishu": "Tempos restantes",
            "mimacuo": "O nome de usuário ou senha não está correto",
            "denglu": "Conecte-se",
            "shumima": "Por favor insira a senha",
            "shuzhanghu": "Por favor, digite a conta.",
            "wangjimima": "Digite o nome da conta",
            "password": "senha",
            "zhanghu": "conta",
            "qingdenglu": "Por favor entre.",
            "nolianjie": "Desconectado",
            "shuruidshebei": "Digite o nome / ID do dispositivo para encontrar o dispositivo",
            "wodezhanghu": "Minha conta",
            "xuanzejiqi": "Selecione a máquina on-line atual",
            "moshi2": "modelo 2",
            "moshi1": "modelo 1",
            "moshi0": "modelo 0",
            "zhongzhi": "Redefinir",
            "kelu": "Cortar",
            "shike": "Teste de corte",
            "gengxintime": "Hora da última atualização",
            "xianwei": "Limite",
            "fukuan": "Largura de corte",
            "chulunbi": "Escala",
            "daoya": "Pressão da faca",
            "shebeixinxi": "Informação de dispositivo",
            "daosu": "Velocidade de corte",
            "shuaxinshuju": "Atualizar dados da máquina",
            "shebeihao": "Número do dispositivo",
            "zhinengqiemo": "Corte de filme inteligente",
            "noshebei": "Nenhum dispositivo disponível foi encontrado",
            "setdaosucuo": "erro de configuração da velocidade da ferramenta",
            "setdaoyacuo": "erro de ajuste da pressão da ferramenta",
            "keluchucuo": "Erro de corte",
            "cutting": "Corte de filme",
            "querenqiege": "Confirmar a cortar",
            "settishi": "Defina primeiro a pressão e a velocidade da ferramenta",
            "tianjiaok": "Adicionado com sucesso",
            "setdaosu": "Definir velocidade de corte",
            "jianchakelu": "Verifique o status de corte do dispositivo",
            "jianchazaixian": "Verificar o status online do dispositivo",
            "close": "Fechar",
            "chulizhong": "Corte de processamento de dados",
            "lijiqiemo": "Cortar agora",
            "lixian": "O dispositivo está offline",
            "weibangdin": "Não consolidado",
            "back": "Retorna",
            "shuoming": "instruções de corte",
            "sudu": "Rapidez",
            "tianjiachangyon": "Adicionar como comum",
            "canshu": "Parâmetros de corte",
            "xiangqing": "Detalhes de corte",
            "ip2": "IP dispositivo:",
            "xuliehao2": "Criar número de série:",
            "shiyonzhong": "em uso",
            "zhaobudao": "Nenhum dispositivo encontrado",
            "zhengzaisousuo": "Procurando",
            "tianjiashebei": "Adicionar Dispositivo",
            "shebei": "Lista de dispositivos",
            "setok": "Configurar com sucesso",
            "startset": "Configuração",
            "jiance": "Detectar o modo AP desconectado",
            "changshi": "Tente conectar",
            "ok": "Concluir",
            "tspassword": "Digite a senha do WiFi",
            "tishiwifiname": "Digite o nome do WiFi",
            "next": "Próxima Etapa",
            "wifipassword": "Senha do wifi",
            "wifiname": "Nome WiFi",
            "quebao": "Verifique se já está conectado ao ponto de acesso do dispositivo",
            "peizhiwifi": "Configurar WiFi",
            "peizhifangshi": "Selecione o modo de configuração",
            "sousuo": "Pesquisar dispositivo",
            "peiwang": "Definir WiFi para o dispositivo",
            "xinhao": "Modelo",
            "pinpai": "Marca",
            "xieyi": "Descrição do contrato",
            "shiyoncishu": "Usando o tempo para lâminas",
            "dianyuan": "Fonte de energia",
            "ip": "endereço de IP",
            "xuliehao": "Número de série do dispositivo",
            "banbenhao": "Número da versão",
            "qiemoji": "Cortador de filme protetor inteligente",
            "sz": "Configuração",
            "lang": "Língua",
            "authlogin": "Login autorizado",
            "emailnoreg": "O email não está registrado",
            "mobilenoreg": "O número do celular não está registrado",
            "resetsuccess": "Redefinir com sucesso, faça login novamente",
            "diffpassword": "A senha digitada é diferente",
            "loginnameempty": "O nome de usuário está vazio, digite novamente!",
            "loginnameisused": "O nome de usuário já está sendo usado, por favor preencha novamente!",
            "registrysuccess": "Registrado com sucesso",
            "passwordshort": "A senha tem menos de 6 caracteres, digite novamente a senha",
            "verifyincorrect": "Erro no código de verificação, tente novamente",
            "emailuse": "O email foi usado",
            "mobileuse": "O número do celular foi usado",
            "mobilenouseincorrect": "O número do celular está incorreto. Digite novamente!",
            "sendverifycodefail": "Falha ao enviar o código de verificação. Tente novamente mais tarde",
            "verifycodesent": "O código de verificação foi enviado, verifique-o",
            "noqrcode": "Nenhum código QR",
            "forgetemail": "Modificar email",
            "forgetphone": "Modificar número de telefone celular",
            "emailyanzhengma": "Faça login no e-mail para obter o código de verificação e digite",
            "editingemail": "O email",
            "enteremail": "Por favor introduza o seu e-mail",
            "register": "Registro",
            "resetyanzhengma": "Reenviar",
            "sendyanzhengma": "",
            "getyanzhengma": "Obter código de verificação",
            "enteryanzhengma": "Digite o código de verificação",
            "yanzhengma": "Código de verificação",
            "enterphone": "Digite o número do celular",
            "editingphone": "Número de celular",
            "passwordlen": "Por favor insira a senha",
            "entername": "Digite o nome de usuário",
            "editingname": "Nome do usuário",
            "emailregister": "Registre-se com E-mail",
            "phoneregister": "Registre-se com número de celular",
            "xinyonhuzhuce": "Registro",
            "amount": "Montante",
            "scanpay": "Por favor, use wechat para pagar!",
            "loadmore": "Carregue mais",
            "quicksearch": "Pesquisa rápida",
            "wifipermission": "Por favor, permita a leitura do wifi e ative o wifi nas permissões do aplicativo",
            "selectwifi": "Escolha wifi",
            "cutfail": "Error al cargar el archivo.",
            "downloadfail": "Falha no download do arquivo",
            "setpressurefail": "Falha ao definir a força de corte",
            "setspeedfail": "Falha ao definir a velocidade",
            "app_name": "CloudCutter",
            "paymentsuccess": "Pagamento bem sucedido",
            "confirmrecharge": "Se deve confirmar a recarga",
            "search": "Procurar",
            "qr": "confirme",
            "qrtcdl": "Tem certeza de sair?",
            "home": "Página inicial",
            "sbpw": "Definir WiFi",
            "wdsb": "O meu aparelho",
            "qrsc": "Confirmar exclusão?",
            "sc": "Excluir",
            "bc": "Salve ",
            "wzdsb": "Nenhum dispositivo encontrado",
            "ytjsb": "O dispositivo foi adicionado",
            "ycz": "Adicionado à lista comum, não adicione repetidamente",
            "sccg": "Excluir com sucesso",
            "jqzt": "Máquina OK, ocioso",
            "klz":"Em funcionamento",
            "exitapp":"Back again will exit app",
            "nonetwork":"Please check your network"
          },
          "deu": {
            "setyuyan": "Spracheinstellungen",
            "huanyin": "Willkommen bei Intelligent Protective Film Cutter",
            "qssjh": "Bitte geben sie ihre Mobiltelefonnummer ein",
            "qsxm": "Bitte geben sie einen Benutzernamen ein",
            "qd": "bestätigen",
            "qsrzhmm": "Bitte geben Sie das Passwort ein",
            "zuihousj": "Geräte zuletzt aktualisiert",
            "moren": "Standard",
            "qcz": "Aufladen",
            "cishu": "Schnittzeiten",
            "xiugai": "Ändern",
            "csbzqcz": "Unzureichende Schnittzeiten, bitte aufladen",
            "fsklwj": "Datei ausschneiden",
            "sxz": "Erfrischend",
            "sxzt": "Status aktualisieren",
            "user": "Verwenden",
            "gybj": "Über diese Maschine",
            "wxts": "Tipps: Um Ihre Rechte und Interessen zu schützen, geben Sie bitte Ihre persönlichen Daten ein. Wenn Sie Ihr Passwort vergessen haben, können Sie Ihre persönlichen Daten überprüfen und Ihr Passwort abrufen!",
            "qsdz": "Bitte geben Sie Ihre Adresse ein",
            "qsyx": "Bitte geben Sie ihre E-Mail-Adresse ein",
            "qshm": "Bitte geben sie ihre Mobiltelefonnummer ein",
            "dz": "Adresse",
            "yx": "Email",
            "phone": "Telefonnummer",
            "name": "vollständiger Name",
            "wsgrzl": "Verbessern Sie Ihre persönlichen Daten",
            "tj": "Statistiken",
            "cp": "Produkt",
            "sy": "Startseite",
            "szcsyzmm": "Zum Festlegen von Parametern ist ein Kennwort erforderlich, um Ihre Berechtigungen zu überprüfen",
            "tcdl": "Ausloggen",
            "tsms": "Aktivieren Sie den Debug-Modus",
            "sbpz": "Gerätekonfiguration",
            "grzl": "persönliche Daten",
            "sycs": "Verbleibende Schnittzeiten",
            "wode": "Meine",
            "sp": "Ware",
            "jsgy": "Letzte 3 Monate",
            "jygy": "Letzte 1 Monate",
            "jqt": "Letzte 7 Tage",
            "xl": "Verkaufsvolumen",
            "rq": "Datum",
            "spxl": "Commodity Verkaufsvolumen",
            "mrxl": "Tägliches Verkaufsvolumen",
            "fenlei": "Klassifizierung",
            "sksb": "Testschnitt fehlgeschlagen. Überprüfen Sie, ob das Gerät ordnungsgemäß mit dem Netzwerk verbunden ist",
            "zlxd": "Probeschneiden",
            "cyxh": "Gemeinsame Modelle",
            "remenxh": "Beliebte Modelle",
            "nownobang": "Derzeit sind keine Geräte gebunden",
            "lx": "Offline",
            "zaixian": "Online",
            "yilianjie": "Gerät ist verbunden",
            "sousuozhong": "Gerätesuche",
            "czok": "Zurücksetzen erfolgreich",
            "querencz": "Müssen Sie wirklich zurücksetzen? Die aktuelle Konfiguration des Geräts wird entfernt",
            "geshihua": "Werkseinstellungen wiederherstellen",
            "xianweikaiguan": "Endschalter",
            "sbbuzaixian": "Gerät ist offline",
            "weibangshebei": "Ungebunden an das Gerät",
            "setfukuan": "Schnittbreite",
            "setsudu": "Geschwindigkeit",
            "setcanshu": "Parametereinstellungen",
            "shuzhi": "Wert",
            "daoyaname5": "Schnittdruck 5",
            "daoyaname4": "Schnittdruck 4",
            "daoyaname3": "Schnittdruck 3",
            "daoyaname2": "Schnittdruck 2",
            "daoyaname1": "Schnittdruck 1",
            "setdaoya": "Schnittkrafteinstellung",
            "yzhou": "Y-Achse",
            "xzhou": "X-Achse",
            "shebeilixian": "Gerät ist offline",
            "nobang": "Ungebunden an das Gerät",
            "setchilunbi": "Skaleneinstellung",
            "jieguo": "Fehler der messer.",
            "quxiao": "stornieren",
            "shuhao": "Bitte geben Sie die Schlüsselwörter der Marke / des Modells ein",
            "chongqianno": "Auf schneiden und",
            "chongqianok": "Bestätigt verstümmelung",
            "nowchong": "Zahlen Sie jetzt",
            "qianxieyi": "Vereinbarung aufladen",
            "tongyi": "Klicken Sie auf Jetzt bezahlen, um zu bestätigen, dass Sie den Zahlungsvereinbarungsbedingungen zustimmen.",
            "qian3": "3 Nach dem Aufladen erfolgt keine Rückerstattung!",
            "qian2": "2 Die Anzahl der Schnittzeiten kann nicht gegen Bargeld eingetauscht, abgehoben oder auf andere übertragen werden.",
            "qian1": "1 Die Kaufzeiten können zum Folienschneiden verwendet werden.",
            "tishi": "Tipps",
            "xuanqian": "Bitte wählen Sie den Aufladebetrag",
            "tijiaook": "Senden Sie erfolgreich",
            "queren": "Bestätigen Sie die Übermittlung",
            "huifu": "Nicht mit",
            "lishifankui": "Rückmeldungen zur Geschichte",
            "tianyijian": "Bitte geben Sie hier Ihre Kommentare und Vorschläge ein",
            "tijiao": "einreichen",
            "fankui": "Feedback",
            "chongqian": "Aufladen",
            "qiemojilu": "Rekord schneiden",
            "chongzhijilu": "Rekord aufladen",
            "shengcishu": "Verbleibende Zeiten",
            "mimacuo": "Seriennummer des laufwerks",
            "denglu": "Einloggen",
            "shumima": "Bitte geben Sie das Passwort ein",
            "shuzhanghu": "Bitte geben Sie den Kontonamen ein",
            "wangjimima": "Passwort vergessen",
            "password": "Passwort",
            "zhanghu": "Konto",
            "qingdenglu": "Bitte loggen Sie sich ein",
            "nolianjie": "Nicht verbunden",
            "shuruidshebei": "Bitte geben Sie den Gerätenamen / die ID ein, um das Gerät zu finden",
            "wodezhanghu": "Mein Konto",
            "xuanzejiqi": "Wählen Sie den aktuellen Online-Computer aus",
            "moshi2": "Modus 2",
            "moshi1": "Modus 1",
            "moshi0": "Modus 0",
            "zhongzhi": "Zurücksetzen",
            "kelu": "Schnitt",
            "shike": "Probeschneiden",
            "gengxintime": "Letzte Aktualisierung",
            "xianwei": "Grenze",
            "fukuan": "Schnittbreite",
            "chulunbi": "Rahmen",
            "daoya": "Messerdruck",
            "shebeixinxi": "Geräteinformation",
            "daosu": "Schneidgeschwindigkeit",
            "shuaxinshuju": "Maschinendaten aktualisieren",
            "shebeihao": "Gerätenummer",
            "zhinengqiemo": "Intelligentes Filmschneiden",
            "noshebei": "Es wurden keine verfügbaren Geräte gefunden",
            "setdaosucuo": "Werkzeuggeschwindigkeitseinstellung Fehler",
            "setdaoyacuo": "Werkzeugdruckeinstellung Fehler",
            "keluchucuo": "Schnittfehler",
            "cutting": "Film schneiden",
            "querenqiege": "Schnitt bestätigen",
            "settishi": "Bitte stellen Sie zuerst den Werkzeugdruck und die Geschwindigkeit ein",
            "tianjiaok": "Erfolgreich hinzugefügt",
            "setdaosu": "Schnittgeschwindigkeit einstellen",
            "jianchakelu": "Überprüfen Sie den Schneidestatus des Geräts",
            "jianchazaixian": "Überprüfen Sie den Online-Status des Geräts",
            "close": "Schließen",
            "chulizhong": "Schnittdatenverarbeitung",
            "lijiqiemo": "Jetzt schneiden",
            "lixian": "Gerät ist offline",
            "weibangdin": "Ungebunden",
            "back": "Rückkehr",
            "shuoming": "Schnittanleitung",
            "sudu": "Geschwindigkeit",
            "tianjiachangyon": "Wie üblich hinzufügen",
            "canshu": "Schnittparameter",
            "xiangqing": "Details des Schneidens",
            "ip2": "Geräte-IP:",
            "xuliehao2": "Seriennummer des Geräts:",
            "shiyonzhong": "in Benutzung",
            "zhaobudao": "Kein Gerät gefunden",
            "zhengzaisousuo": "Suchen",
            "tianjiashebei": "Gerät hinzufügen",
            "shebei": "Geräteliste",
            "setok": "Richten Sie erfolgreich ein",
            "startset": "Installieren",
            "jiance": "Erkennen Sie den nicht verbundenen AP-Modus",
            "changshi": "Versuchen Sie, eine Verbindung herzustellen",
            "ok": "Vervollständigen",
            "tspassword": "Bitte geben Sie das WLAN-Passwort ein",
            "tishiwifiname": "Bitte geben Sie den WLAN-Namen ein",
            "next": "Nächster Schritt",
            "wifipassword": "WLAN Passwort",
            "wifiname": "WiFi Name",
            "quebao": "Stellen Sie sicher, dass bereits eine Verbindung mit dem Geräte-Hotspot besteht",
            "peizhiwifi": "WLAN konfigurieren",
            "peizhifangshi": "Konfigurationsmodus auswählen",
            "sousuo": "Gerät suchen",
            "peiwang": "WLAN für Gerät einstellen",
            "xinhao": "Modell",
            "pinpai": "Marke",
            "xieyi": "Beschreibung der Vereinbarung",
            "shiyoncishu": "Zeit für Klingen nutzen",
            "dianyuan": "Energieversorgung",
            "ip": "IP Adresse",
            "xuliehao": "Seriennummer des Geräts",
            "banbenhao": "Versionsnummer",
            "qiemoji": "Intelligenter Schutzfilmschneider",
            "sz": "Installieren",
            "lang": "Sprache",
            "authlogin": "Autorisierte Anmeldung",
            "emailnoreg": "E-Mail ist nicht registriert",
            "mobilenoreg": "Handynummer ist nicht registriert",
            "resetsuccess": "Erfolgreich zurücksetzen, bitte erneut anmelden",
            "diffpassword": "Das eingegebene Passwort ist unterschiedlich",
            "loginnameempty": "Benutzername ist leer, bitte erneut eingeben!",
            "loginnameisused": "Der Benutzername wird bereits verwendet, bitte erneut eingeben!",
            "registrysuccess": "Erfolgreich registriert",
            "passwordshort": "Das Passwort besteht aus weniger als 6 Zeichen. Bitte geben Sie das Passwort erneut ein",
            "verifyincorrect": "Bestätigungscode-Fehler, bitte versuchen Sie es erneut",
            "emailuse": "E-Mail wurde verwendet",
            "mobileuse": "Handynummer wurde verwendet",
            "mobilenouseincorrect": "Handynummer ist falsch, bitte erneut eingeben!",
            "sendverifycodefail": "Fehler beim Senden des Bestätigungscodes. Bitte versuchen Sie es später erneut",
            "verifycodesent": "Der Bestätigungscode wurde gesendet. Bitte überprüfen Sie ihn",
            "noqrcode": "Kein QR-Code",
            "forgetemail": "E-Mail ändern",
            "forgetphone": "Handynummer ändern",
            "emailyanzhengma": "Bitte melden Sie sich per E-Mail an, um den Bestätigungscode zu erhalten, und geben Sie ein",
            "editingemail": "Email",
            "enteremail": "Bitte geben Sie ihre E-Mail-Adresse ein",
            "register": "Registrieren",
            "resetyanzhengma": "Erneut senden",
            "sendyanzhengma": "",
            "getyanzhengma": "Bestätigungscode abrufen",
            "enteryanzhengma": "Bitte geben Sie den Bestätigungscode ein",
            "yanzhengma": "Verifizierungs-Schlüssel",
            "enterphone": "Bitte geben Sie die Handynummer ein",
            "editingphone": "Handynummer",
            "passwordlen": "Bitte geben Sie das Passwort ein",
            "entername": "Bitte geben sie einen Benutzernamen ein",
            "editingname": "Nutzername",
            "emailregister": "Registrieren mit E-Mail",
            "phoneregister": "Registrieren Sie sich mit der Handynummer",
            "xinyonhuzhuce": "Registrieren",
            "amount": "Menge",
            "scanpay": "Bitte benutze Wechat um zu bezahlen!",
            "loadmore": "Mehr laden",
            "quicksearch": "Schnelle Suche",
            "wifipermission": "Bitte erlauben Sie das Lesen von WLAN und aktivieren Sie WLAN in App-Berechtigungen",
            "selectwifi": "Wählen Sie WLAN",
            "cutfail": "Datei-Upload fehlgeschlagen",
            "downloadfail": "Dateidownload fehlgeschlagen",
            "setpressurefail": "Schnittkraft konnte nicht eingestellt werden",
            "setspeedfail": "Geschwindigkeit konnte nicht eingestellt werden",
            "app_name": "CloudCutter",
            "paymentsuccess": "Pay war erfolgreich",
            "confirmrecharge": "Gibt an, ob das Aufladen bestätigt werden soll",
            "search": "Suche",
            "qr": "bestätigt",
            "qrtcdl": "Sicher abmelden?",
            "home": "Zuhause",
            "sbpw": "Stellen Sie WiFi ein",
            "wdsb": "Mein Gerät",
            "qrsc": "Löschen bestätigen?",
            "sc": "Löschen",
            "bc": "speichern",
            "wzdsb": "Kein Gerät gefunden",
            "ytjsb": "Das Gerät wurde hinzugefügt",
            "ycz": "Zur allgemeinen Liste hinzugefügt, bitte nicht wiederholt hinzufügen",
            "sccg": "Erfolgreich löschen",
            "jqzt": "Maschine OK, Leerlauf",
            "klz":"In Betrieb",
            "exitapp":"Back again will exit app",
            "nonetwork":"Please check your network"
          },
          "fra": {
            "setyuyan": "Paramètres de langue",
            "huanyin": "Bienvenue sur Intelligent Protective Film Cutter",
            "qssjh": "Entrez s''il vous plaît votre numéro de téléphone",
            "qsxm": "veuillez entrer le nom d''utilisateur",
            "qd": "Confirmer",
            "qsrzhmm": "S''il vous plaît entrer le mot de passe",
            "zuihousj": "Dernière mise à jour de l''appareil",
            "moren": "Défaut",
            "qcz": "Recharger",
            "cishu": "Temps de coupe",
            "xiugai": "Modifier",
            "csbzqcz": "Temps de coupe insuffisants, veuillez recharger",
            "fsklwj": "Envoyer le fichier coupé",
            "sxz": "Rafraîchir",
            "sxzt": "Actualiser le statut",
            "user": "Utilisation",
            "gybj": "À propos de cette machine",
            "wxts": "Conseils: Pour protéger vos droits et intérêts, veuillez compléter vos informations personnelles. Si vous oubliez votre mot de passe, vous pouvez vérifier vos informations personnelles et récupérer votre mot de passe!",
            "qsdz": "Veuillez entrer votre adresse",
            "qsyx": "Veuillez saisir votre email",
            "qshm": "Entrez s''il vous plaît votre numéro de téléphone",
            "dz": "adresse",
            "yx": "Email",
            "phone": "numéro de téléphone",
            "name": "nom complet",
            "wsgrzl": "Améliorez vos informations personnelles",
            "tj": "Estatisticas",
            "cp": "produit",
            "sy": "Page d''accueil",
            "szcsyzmm": "La définition des paramètres nécessite un mot de passe pour vérifier vos autorisations",
            "tcdl": "Se déconnecter",
            "tsms": "Entrer en mode débogage",
            "sbpz": "Configuration de l''appareil",
            "grzl": "Données personnelles",
            "sycs": "Temps de coupe restants",
            "wode": "Le mien",
            "sp": "marchandise",
            "jsgy": "3 derniers mois",
            "jygy": "1 derniers mois",
            "jqt": "7 derniers jours",
            "xl": "volume des ventes",
            "rq": "date",
            "spxl": "Volume des ventes de produits de base",
            "mrxl": "Volume des ventes quotidiennes",
            "fenlei": "classification",
            "sksb": "Le test de découpe a échoué, veuillez vérifier si la machine est normalement connectée au réseau",
            "zlxd": "Coupe d''essai",
            "cyxh": "Modèles courants",
            "remenxh": "Modèles populaires",
            "nownobang": "Aucun appareil n''est actuellement lié",
            "lx": "Hors ligne",
            "zaixian": "En ligne",
            "yilianjie": "L''appareil est connecté",
            "sousuozhong": "Recherche d''appareils",
            "czok": "Réinitialisation réussie",
            "querencz": "Voulez-vous vraiment réinitialiser? La configuration actuelle de l''appareil sera supprimée",
            "geshihua": "Rétablir les paramètres d''usine",
            "xianweikaiguan": "Fin de course",
            "sbbuzaixian": "L''appareil est hors ligne",
            "weibangshebei": "Non lié à l''appareil",
            "setfukuan": "Largeur de coupe",
            "setsudu": "La vitesse",
            "setcanshu": "Réglages des paramètres",
            "shuzhi": "Valeur",
            "daoyaname5": "Pression de coupe 5",
            "daoyaname4": "Pression de coupe 4",
            "daoyaname3": "Pression de coupe 3",
            "daoyaname2": "Pression de coupe 2",
            "daoyaname1": "Pression de coupe 1",
            "setdaoya": "Réglage de la force de coupe",
            "yzhou": "Axe Y",
            "xzhou": "Axe X",
            "shebeilixian": "L''appareil est hors ligne",
            "nobang": "Non lié à l''appareil",
            "setchilunbi": "Réglage de l''échelle",
            "jieguo": "Résultats de la recherche",
            "quxiao": "Annuler",
            "shuhao": "Veuillez saisir des mots clés de marque / modèle",
            "chongqianno": "Fallo de recarga",
            "chongqianok": "Recharge réussie!",
            "nowchong": "Payez maintenant",
            "qianxieyi": "Accord de recharge",
            "tongyi": "Cliquez sur Payer maintenant signifie que vous acceptez les conditions de l''accord de paiement.",
            "qian3": "3 Après la recharge, aucun remboursement!",
            "qian2": "2.Le nombre de coupes ne peut pas être échangé contre de l''argent, retiré ou transféré à d''autres.",
            "qian1": "1. le nombre d’achats peut être utilisé lors du découpage des membranes.",
            "tishi": "Conseils",
            "xuanqian": "Veuillez sélectionner le montant de la recharge",
            "tijiaook": "Soumettre avec succès",
            "queren": "Confirmer la soumission",
            "huifu": "Réponse:",
            "lishifankui": "Commentaires sur l''historique",
            "tianyijian": "Veuillez remplir vos commentaires et suggestions ici",
            "tijiao": "Soumettre",
            "fankui": "Retour d''information",
            "chongqian": "Recharger",
            "qiemojilu": "Record de coupe",
            "chongzhijilu": "Dossier de recharge",
            "shengcishu": "Temps restant",
            "mimacuo": "Le nom d’utilisateur ou le mot de passe ne sont pas corrects",
            "denglu": "S''identifier",
            "shumima": "Veuillez introduire votre mot de passe",
            "shuzhanghu": "Veuillez indiquer le compte",
            "wangjimima": "Mot de passe oublié",
            "password": "Mot de passe",
            "zhanghu": "Les comptes",
            "qingdenglu": "Veuillez vous connecter",
            "nolianjie": "Sans rapport",
            "shuruidshebei": "Veuillez saisir le nom / ID de l''appareil pour trouver l''appareil",
            "wodezhanghu": "Mon compte",
            "xuanzejiqi": "Sélectionnez la machine en ligne actuelle",
            "moshi2": "Mode 2",
            "moshi1": "Mode 1",
            "moshi0": "Mode 0",
            "zhongzhi": "Réinitialiser",
            "kelu": "Couper",
            "shike": "Coupe d''essai",
            "gengxintime": "Heure de la dernière mise à jour",
            "xianwei": "Limite",
            "fukuan": "Largeur de coupe",
            "chulunbi": "Échelle",
            "daoya": "Pression des couteaux",
            "shebeixinxi": "Informations sur l''appareil",
            "daosu": "Vitesse de coupe",
            "shuaxinshuju": "Actualiser les données de la machine",
            "shebeihao": "Numéro de l’appareil",
            "zhinengqiemo": "Découpe de film intelligente",
            "noshebei": "Aucun appareil disponible n''a été trouvé",
            "setdaosucuo": "erreur de réglage de la vitesse de l''outil",
            "setdaoyacuo": "Erreur de réglage de la pression de l''outil",
            "keluchucuo": "Erreur de coupe",
            "cutting": "Découpe de film",
            "querenqiege": "Confirmer la coupe",
            "settishi": "Veuillez d''abord régler la pression et la vitesse de l''outil",
            "tianjiaok": "Ajouté avec succès",
            "setdaosu": "Régler la vitesse de coupe",
            "jianchakelu": "Vérifier l''état de coupe de l''appareil",
            "jianchazaixian": "Vérifier l''état en ligne de l''appareil",
            "close": "Fermer",
            "chulizhong": "Traitement des données de coupe",
            "lijiqiemo": "Coupez maintenant",
            "lixian": "L''appareil est hors ligne",
            "weibangdin": "Non lié",
            "back": "Revenir",
            "shuoming": "instruções de corte",
            "sudu": "La vitesse",
            "tianjiachangyon": "Ajouter comme commun",
            "canshu": "Paramètres de coupe",
            "xiangqing": "Détails de coupe",
            "ip2": "IP de l''appareil:",
            "xuliehao2": "Concevoir le numéro de série:",
            "shiyonzhong": "utilisé",
            "zhaobudao": "Aucun appareil trouvé",
            "zhengzaisousuo": "Recherche",
            "tianjiashebei": "Ajouter un appareil",
            "shebei": "Liste des périphériques",
            "setok": "Configurer avec succès",
            "startset": "Installer",
            "jiance": "Détecter le mode AP non connecté",
            "changshi": "Essayez de vous connecter",
            "ok": "Achevé",
            "tspassword": "Veuillez entrer le mot de passe WiFi",
            "tishiwifiname": "Veuillez entrer le nom WiFi",
            "next": "L''étape suivante",
            "wifipassword": "Mot de passe WiFi",
            "wifiname": "Nom WiFi",
            "quebao": "Assurez-vous que vous êtes déjà connecté au point d''accès de l''appareil",
            "peizhiwifi": "Configurer le WiFi",
            "peizhifangshi": "Sélectionnez le mode de configuration",
            "sousuo": "Appareil de recherche",
            "peiwang": "Définir le WiFi pour l''appareil",
            "xinhao": "Modèle",
            "pinpai": "Marque",
            "xieyi": "Description de l''accord",
            "shiyoncishu": "Utiliser le temps pour les lames",
            "dianyuan": "Source de courant",
            "ip": "adresse IP",
            "xuliehao": "Numéro de série de l''appareil",
            "banbenhao": "Numéro de version",
            "qiemoji": "Coupe-film de protection intelligent",
            "sz": "Installer",
            "lang": "Langue",
            "authlogin": "Connexion autorisée",
            "emailnoreg": "L''email n''est pas enregistré",
            "mobilenoreg": "Le numéro de mobile n''est pas enregistré",
            "resetsuccess": "Réinitialiser avec succès, veuillez vous reconnecter",
            "diffpassword": "Le mot de passe saisi est différent",
            "loginnameempty": "Le nom d''utilisateur est vide, veuillez entrer à nouveau!",
            "loginnameisused": "Le nom d''utilisateur est déjà utilisé, veuillez le remplir à nouveau!",
            "registrysuccess": "Enregistré avec succès",
            "passwordshort": "Le mot de passe contient moins de 6 caractères, veuillez ressaisir le mot de passe",
            "verifyincorrect": "Erreur de code de vérification, veuillez réessayer",
            "emailuse": "L''e-mail a été utilisé",
            "mobileuse": "Le numéro de mobile a été utilisé",
            "mobilenouseincorrect": "Le numéro de téléphone portable est erroné, veuillez entrer à nouveau!",
            "sendverifycodefail": "Échec de l''envoi du code de vérification, veuillez réessayer plus tard",
            "verifycodesent": "Le code de vérification a été envoyé, veuillez le vérifier",
            "noqrcode": "Pas de code QR",
            "forgetemail": "Modifier l''e-mail",
            "forgetphone": "Modifier le numéro de téléphone mobile",
            "emailyanzhengma": "Veuillez vous connecter par e-mail pour obtenir le code de vérification et entrez",
            "editingemail": "Email",
            "enteremail": "Veuillez saisir votre email",
            "register": "S''inscrire",
            "resetyanzhengma": "Renvoyer",
            "sendyanzhengma": "",
            "getyanzhengma": "Obtenez le code de vérification",
            "enteryanzhengma": "Veuillez saisir le code de vérification",
            "yanzhengma": "Code de vérification",
            "enterphone": "Veuillez saisir le numéro de mobile",
            "editingphone": "Numéro de portable",
            "passwordlen": "S''il vous plaît entrer le mot de passe",
            "entername": "Veuillez saisir un nom d''utilisateur",
            "editingname": "Nom d''utilisateur",
            "emailregister": "S''inscrire avec e-mail",
            "phoneregister": "S''inscrire avec un numéro de mobile",
            "xinyonhuzhuce": "S''inscrire",
            "amount": "Montant",
            "scanpay": "Veuillez utiliser wechat pour payer!",
            "loadmore": "Charger plus",
            "quicksearch": "Recherche rapide",
            "wifipermission": "Veuillez autoriser la lecture du wifi et activer le wifi dans les autorisations de l''application",
            "selectwifi": "Choisissez le wifi",
            "cutfail": "Falha no upload do arquivo",
            "downloadfail": "Le téléchargement du fichier a échoué",
            "setpressurefail": "Impossible de régler la force de coupe",
            "setspeedfail": "Impossible de définir la vitesse",
            "app_name": "CloudCutter",
            "paymentsuccess": "Paiement réussi",
            "confirmrecharge": "Que ce soit pour confirmer la recharge",
            "search": "Chercher",
            "qr": "Confirmer",
            "qrtcdl": "Vous êtes sûr de vous déconnecter?",
            "home": "Accueil",
            "sbpw": "Définir le WiFi",
            "wdsb": "Mon appareil",
            "qrsc": "Confirmation de la suppression?",
            "sc": "Supprimer",
            "bc": "sauvegarder",
            "wzdsb": "Aucun appareil trouvé",
            "ytjsb": "L''appareil a été ajouté",
            "ycz": "Ajouté à la liste commune, veuillez ne pas ajouter à plusieurs reprises",
            "sccg": "Supprimer avec succès",
            "jqzt": "Machine normale",
            "klz":"En cours",
            "exitapp":"Back again will exit app",
            "nonetwork":"Please check your network"
          },
          "py": {
            "setyuyan": "языковые настройки",
            "huanyin": "Добро пожаловать в Интеллектуальный Резак Защитной Пленки",
            "qssjh": "Пожалуйста, введите номер вашего мобильного телефона",
            "qsxm": "пожалуйста, введите имя пользователя",
            "qd": "подтверждения",
            "qsrzhmm": "Пожалуйста, введите пароль",
            "zuihousj": "Время последнего обновления устройства",
            "moren": "дефолт",
            "qcz": "Перезарядить",
            "cishu": "Время резки",
            "xiugai": "Изменить",
            "csbzqcz": "Недостаточное время резки, пожалуйста, зарядите",
            "fsklwj": "Отправить вырезанный файл",
            "sxz": "Освежающий",
            "sxzt": "Обновить статус",
            "user": "использование",
            "gybj": "Об этой машине",
            "wxts": "Советы: Чтобы защитить свои права и интересы, пожалуйста, заполните свои личные данные. Если вы забыли свой пароль, вы можете проверить свою личную информацию и восстановить свой пароль!",
            "qsdz": "Пожалуйста, введите ваш адрес",
            "qsyx": "Пожалуйста, введите ваш адрес электронной почты",
            "qshm": "Пожалуйста, введите номер вашего мобильного телефона",
            "dz": "адрес",
            "yx": "Эл. адрес",
            "phone": "номер телефона",
            "name": "ФИО",
            "wsgrzl": "Улучшить вашу личную информацию",
            "tj": "Статистика",
            "cp": "продукт",
            "sy": "домашняя страница",
            "szcsyzmm": "Настройка параметров требует пароль для проверки ваших разрешений",
            "tcdl": "Выйти",
            "tsms": "Войдите в режим отладки",
            "sbpz": "Конфигурация устройства",
            "grzl": "Персональные данные",
            "sycs": "Оставшееся время резки",
            "wode": "мой",
            "sp": "товар",
            "jsgy": "Последние 3 месяца",
            "jygy": "Последние 1 месяца",
            "jqt": "Последние 7 дней",
            "xl": "объем продаж",
            "rq": "Дата",
            "spxl": "Товарооборот",
            "mrxl": "Ежедневный объем продаж",
            "fenlei": "классификация",
            "sksb": "Не удалось выполнить пробную резку. Проверьте, нормально ли подключен станок к сети.",
            "zlxd": "Пробная резка",
            "cyxh": "Общие модели",
            "remenxh": "Популярные модели",
            "nownobang": "В данный момент нет привязанных устройств",
            "lx": "Не в сети",
            "zaixian": "В сети",
            "yilianjie": "Устройство подключено",
            "sousuozhong": "Поиск устройства",
            "czok": "Сброс выполнен успешно",
            "querencz": "Вы уверены, что сбросить? Текущая конфигурация устройства будет удалена",
            "geshihua": "Восстановить заводские настройки",
            "xianweikaiguan": "Концевой выключатель",
            "sbbuzaixian": "Устройство не в сети",
            "weibangshebei": "Не привязан к устройству",
            "setfukuan": "Ширина вырезывания",
            "setsudu": "скорость",
            "setcanshu": "Настройки параметров",
            "shuzhi": "численный",
            "daoyaname5": "Давление вырезывания 5",
            "daoyaname4": "Давление вырезывания 4",
            "daoyaname3": "Давление вырезывания 3",
            "daoyaname2": "Давление вырезывания 2",
            "daoyaname1": "Давление вырезывания 1",
            "setdaoya": "Настройка силы резания",
            "yzhou": "Ось Y",
            "xzhou": "Ось X",
            "shebeilixian": "Устройство не в сети",
            "nobang": "Не привязан к устройству",
            "setchilunbi": "Настройка масштаба",
            "jieguo": "Результаты поиска.",
            "quxiao": "отмен",
            "shuhao": "Пожалуйста, введите ключевые слова бренда / модели",
            "chongqianno": "Пополнение не удалось",
            "chongqianok": "Пополнение прошло успешно",
            "nowchong": "Заплатить сейчас.",
            "qianxieyi": "Соглашение о пополнении счета",
            "tongyi": "Нажмите «Оплатить сейчас» означает, что вы согласны с условиями соглашения об оплате.",
            "qian3": "3 После зарядки нет возврата!",
            "qian2": "2 Количество сокращений не может быть обменено на наличные деньги, снято или передано другим лицам.",
            "qian1": "1 Время покупки может быть использовано для резки пленки.",
            "tishi": "подсказки",
            "xuanqian": "Пожалуйста, выберите сумму пополнения",
            "tijiaook": "Отправить успешно",
            "queren": "Подтвердите отправку",
            "huifu": "Ответ:",
            "lishifankui": "История Обратная связь",
            "tianyijian": "Пожалуйста, заполните ваши комментарии и предложения здесь …",
            "tijiao": "Разместить",
            "fankui": "Обратная связь",
            "chongqian": "перезарядка",
            "qiemojilu": "Реза мембра запис",
            "chongzhijilu": "Запись пополнения",
            "shengcishu": "Оставшиеся времена",
            "mimacuo": "Логин ил парол некорректн",
            "denglu": "Авторизоваться",
            "shumima": "Пожалуйста, введите пароль",
            "shuzhanghu": "Пожалуйста, введите имя учетной записи",
            "wangjimima": "Забыл пароль",
            "password": "пароль",
            "zhanghu": "учетная запись",
            "qingdenglu": "Пожалуйста, войдите",
            "nolianjie": "несвязанный",
            "shuruidshebei": "Пожалуйста, введите имя устройства / идентификатор, чтобы найти устройство",
            "wodezhanghu": "Мой аккаунт",
            "xuanzejiqi": "Выберите текущий онлайн-компьютер",
            "moshi2": "Режим 2",
            "moshi1": "Режим 1",
            "moshi0": "Режим 0",
            "zhongzhi": "Сброс настроек",
            "kelu": "Порез",
            "shike": "Тест резки",
            "gengxintime": "Время последнего обновления",
            "xianwei": "предел",
            "fukuan": "Ширина резки",
            "chulunbi": "Масштаб",
            "daoya": "Давление ножа",
            "shebeixinxi": "Информация об устройстве",
            "daosu": "Скорость резки",
            "shuaxinshuju": "Обновить машинные данные",
            "shebeihao": "Номер устройства",
            "zhinengqiemo": "Интеллектуальная резка пленки",
            "noshebei": "Доступные устройства не найдены",
            "setdaosucuo": "Ошибка настройки скорости инструмента",
            "setdaoyacuo": "Ошибка настройки давления инструмента",
            "keluchucuo": "Ошибка резки",
            "cutting": "Резка пленки",
            "querenqiege": "Подтвердите резку",
            "settishi": "Пожалуйста, сначала установите давление и скорость инструмента",
            "tianjiaok": "Успешно добавлено",
            "setdaosu": "Установить скорость резания",
            "jianchakelu": "Проверьте состояние резки устройства",
            "jianchazaixian": "Проверьте состояние устройства в сети",
            "close": "близко",
            "chulizhong": "Обработка данных резки",
            "lijiqiemo": "Вырезать сейчас",
            "lixian": "Устройство не в сети",
            "weibangdin": "несвязанный",
            "back": "Возвращение",
            "shuoming": "инструкции по резке",
            "sudu": "скорость",
            "tianjiachangyon": "Добавить как общий",
            "canshu": "Параметры резки",
            "xiangqing": "Детали резки",
            "ip2": "IP устройства:",
            "xuliehao2": "Разработать серийный номер:",
            "shiyonzhong": "в использовании",
            "zhaobudao": "Устройство не найдено",
            "zhengzaisousuo": "Поиск",
            "tianjiashebei": "Добавить устройство",
            "shebei": "Список устройств",
            "setok": "Успешно настроен",
            "startset": "Настроить",
            "jiance": "Обнаружить неподключенный режим AP",
            "changshi": "Попробуйте подключиться",
            "ok": "полный",
            "tspassword": "Пожалуйста, введите пароль WiFi",
            "tishiwifiname": "Пожалуйста, введите имя WiFi",
            "next": "Следующий шаг",
            "wifipassword": "Пароль Wi-Fi",
            "wifiname": "Имя WiFi",
            "quebao": "Убедитесь, что уже подключен к точке доступа устройства",
            "peizhiwifi": "Настроить WiFi",
            "peizhifangshi": "Выберите режим конфигурации",
            "sousuo": "Поиск устройства",
            "peiwang": "Установить WiFi для устройства",
            "xinhao": "модель",
            "pinpai": "марка",
            "xieyi": "Описание соглашения",
            "shiyoncishu": "Используя время для лезвий",
            "dianyuan": "Источник питания",
            "ip": "айпи адрес",
            "xuliehao": "Серийный номер устройства",
            "banbenhao": "Номер версии",
            "qiemoji": "Интеллектуальный резак защитной пленки",
            "sz": "Настроить",
            "lang": "язык",
            "authlogin": "Авторизованный вход",
            "emailnoreg": "Электронная почта не зарегистрирована",
            "mobilenoreg": "Мобильный номер не зарегистрирован",
            "resetsuccess": "Сброс успешно, пожалуйста, войдите снова",
            "diffpassword": "Введен другой пароль",
            "loginnameempty": "Имя пользователя пусто, пожалуйста, введите снова!",
            "loginnameisused": "Имя пользователя уже используется, пожалуйста, заполните снова!",
            "registrysuccess": "Регистрация прошла успешно",
            "passwordshort": "Пароль не более 6 символов, пожалуйста, введите пароль еще раз",
            "verifyincorrect": "Ошибка кода подтверждения, пожалуйста, попробуйте еще раз",
            "emailuse": "Электронная почта была использована",
            "mobileuse": "Номер мобильного телефона был использован",
            "mobilenouseincorrect": "Неверный номер мобильного телефона, пожалуйста, введите заново!",
            "sendverifycodefail": "Не удалось отправить код подтверждения, повторите попытку позже",
            "verifycodesent": "Код подтверждения отправлен, пожалуйста, проверьте его",
            "noqrcode": "Нет QR-кода",
            "forgetemail": "Изменить электронную почту",
            "forgetphone": "Изменить номер мобильного телефона",
            "emailyanzhengma": "Пожалуйста, авторизуйтесь по электронной почте, чтобы получить код подтверждения и введите",
            "editingemail": "Эл. адрес",
            "enteremail": "Пожалуйста, введите ваш адрес электронной почты",
            "register": "регистр",
            "resetyanzhengma": "Отправить",
            "sendyanzhengma": "",
            "getyanzhengma": "Получить код подтверждения",
            "enteryanzhengma": "Пожалуйста, введите код подтверждения",
            "yanzhengma": "код подтверждения",
            "enterphone": "Пожалуйста, введите номер мобильного телефона",
            "editingphone": "Мобильный номер",
            "passwordlen": "Пожалуйста, введите пароль",
            "entername": "Пожалуйста, введите имя пользователя",
            "editingname": "имя пользователя",
            "emailregister": "Зарегистрируйтесь через электронную почту",
            "phoneregister": "Зарегистрируйтесь по номеру мобильного телефона",
            "xinyonhuzhuce": "регистр",
            "amount": "деньги",
            "scanpay": "Пожалуйста, используйте wechat для оплаты!",
            "loadmore": "Загрузи больше",
            "quicksearch": "Быстрый поиск",
            "wifipermission": "Пожалуйста, разрешите чтение Wi-Fi и включите Wi-Fi в разрешениях приложения",
            "selectwifi": "Выберите Wi-Fi",
            "cutfail": "Ошибка загрузки файла",
            "downloadfail": "Ошибка загрузки файла",
            "setpressurefail": "Не удалось установить силу резания",
            "setspeedfail": "Не удалось установить скорость",
            "app_name": "CloudCutter",
            "paymentsuccess": "Оплата выполнена",
            "confirmrecharge": "Нужно ли подтвердить пополнение",
            "search": "Поиск",
            "qr": "подтверждает",
            "qrtcdl": "Обязательно выйти?",
            "home": "дома",
            "sbpw": "Установить WiFi",
            "wdsb": "Мое устройство",
            "qrsc": "Подтвердите удаление?",
            "sc": "удалять",
            "bc": "Сохранить",
            "wzdsb": "Устройство не найдено",
            "ytjsb": "Устройство было добавлено",
            "ycz": "Добавлено в общий список, пожалуйста, не добавляйте повторно",
            "sccg": "Удалить успешно",
            "jqzt": "нормальная машина, свободное состояние",
            "klz":"в процессе эксплуатации",
            "exitapp":"Back again will exit app",
            "nonetwork":"Please check your network"
          }
        }
}